_Source/force-app/main/default/objects/BI_Objective_Category__c/BI_Objective_Category__c.object-meta.xml
<CustomObject>
    <label>Objective Category</label>
    <nameField>
        <label>Objective Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Category__c/fields/BI_Active__c.field-meta.xml
<CustomField>
    <fullName>BI_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/BI_Objective_Type__c.object-meta.xml
<CustomObject>
    <label>Objective Type</label>
    <nameField>
        <label>Objective Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Auto_Create_Objective__c.field-meta.xml
<CustomField>
    <fullName>BI_Auto_Create_Objective__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto-Create Objective</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Description__c.field-meta.xml
<CustomField>
    <fullName>BI_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Division__c.field-meta.xml
<CustomField>
    <fullName>BI_Division__c</fullName>
    <label>Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Measure__c.field-meta.xml
<CustomField>
    <fullName>BI_Measure__c</fullName>
    <label>Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Objective_Measure</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Objective_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Objective Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>BI_Objective_Category__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Category__c</referenceTo>
    <relationshipLabel>Objective Types</relationshipLabel>
    <relationshipName>Objective_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Name__c</fullName>
    <label>Objective Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Region__c.field-meta.xml
<CustomField>
    <fullName>BI_Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Region</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Relevant_Plans__c.field-meta.xml
<CustomField>
    <fullName>BI_Relevant_Plans__c</fullName>
    <label>Relevant Plans</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Divisional Plan</fullName>
            </value>
            <value>
                <fullName>Regional Plan</fullName>
            </value>
            <value>
                <fullName>Territory Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Target_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_Target_Date__c</fullName>
    <label>Target Date</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Target_Value__c.field-meta.xml
<CustomField>
    <fullName>BI_Target_Value__c</fullName>
    <label>Target Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/BI_Objectives__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Auto_Created__c.field-meta.xml
<CustomField>
    <fullName>BI_Auto_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Created</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Division__c.field-meta.xml
<CustomField>
    <fullName>BI_Division__c</fullName>
    <description>The Sales Division on the objective owner&apos;s user record</description>
    <formula>TEXT(Owner:User.BI_Objective_Division__c)</formula>
    <inlineHelpText>The Sales Division on the objective owner&apos;s user record</inlineHelpText>
    <label>Division</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_End_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_End_Date__c</fullName>
    <label>Target Date (if known &amp; applicable)</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Focus_Accounts__c.field-meta.xml
<CustomField>
    <fullName>BI_Focus_Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Focus Accounts</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BI_Objective_Category__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Category__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Type</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (((2 AND 3) OR (4 AND 5) OR (6 AND 7)) OR 8 OR 9 OR 10)</booleanFilter>
        <errorMessage>The selected Objective Type is not valid for the type of Plan you are creating this Objective On</errorMessage>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Territory Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Territory Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Regional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Regional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Divisional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Divisional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>notContain</operation>
            <value>Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Account Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Description__c</field>
            <operation>equals</operation>
            <value>(2019)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Type__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Template_Description__c.field-meta.xml
<CustomField>
    <fullName>BI_Template_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Template_Objective_Name_From_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Template_Objective_Name_From_Type__c</fullName>
    <description>This field is used in plan handler classes to update objective names when the plan owner is changed and owner of all objectives should be changed. This field helps update the objective names when the objective owner changed.</description>
    <formula>&quot;BI_Objective_Type__r.BI_Objective_Name__c&quot;</formula>
    <label>Template Objective Name From Type</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Territory_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Territory_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Plan</label>
    <referenceTo>BI_Territory_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/BI_Territory_Plan__c.object-meta.xml
<CustomObject>
    <label>Territory Plan</label>
    <nameField>
        <label>Territory Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/fields/BI_Region__c.field-meta.xml
<CustomField>
    <fullName>BI_Region__c</fullName>
    <formula>Owner:User.Sales_Region__c</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/fields/BI_Territory_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_Territory_Plan_Year__c</fullName>
    <label>Plan Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/classes/BI_TerritoryPlanHandler.cls
/**********************************************************************
Purpose:
-------
Deal with the DML for Regional  Plan

History
-------
VERSION       AUTHOR            DATE              DETAIL               
1.0          Sasi Naik          15/05/2017        INITIAL DEVELOPMENT 
2.0          Yolande Anja       2019 - 11         - populate additional obj type fields for created objectives
                                                  - deal with update obj owner and name when plan owner changes
***********************************************************************/
public class BI_TerritoryPlanHandler implements SIP_Triggers.Handler {
    public static boolean skipErrorMessage = false;
    public List<BI_Territory_Plan__c> Newdp;
    public List<BI_Territory_Plan__c> Oldodp;
    public Map<Id, BI_Territory_Plan__c> mapNewdp;
    public Map<Id, BI_Territory_Plan__c> mapOlddp;
    Map < Id, Id > oldPlanOwners = new Map < Id, Id > (); //map for holding the old plan ownerId 
    Map < Id, Id > newPlanOwners = new Map < Id, Id > (); //map for holding the new plan ownerId

    //This method will initiate the trigger on which event the method need to call
    public void handle() {
        
        if(Trigger.isInsert) {
            Newdp = (List<BI_Territory_Plan__c>)Trigger.new;
            mapNewdp = (Map<Id, BI_Territory_Plan__c>)Trigger.newMap;
        } else if (Trigger.isUpdate) {
            Newdp = (List<BI_Territory_Plan__c>)Trigger.new;
            mapNewdp = (Map<Id, BI_Territory_Plan__c>)Trigger.newMap;
        } 
        
        if(Trigger.isInsert && Trigger.isAfter) {
            //Passing the newmap values to the method to create the plans record in the objective 
            CreateRegplanObjectiveRecord(mapNewdp);
        }
        
        if (Trigger.isUpdate && Trigger.isAfter){
            For(BI_Territory_Plan__c dp : Newdp){
                BI_Territory_Plan__c oldPlan = (BI_Territory_Plan__c)Trigger.oldMap.get(dp.Id);
                Id oldownerId = oldPlan.OwnerId;
                
                if(dp.OwnerId != oldownerId){
                    oldPlanOwners.put(dp.Id, oldownerId);
                    newPlanOwners.put(dp.Id, dp.OwnerId);                    
                }
            }
        }
        
        if(!oldPlanOwners.isEmpty() && !newPlanOwners.isEmpty()){
            system.debug('--------old owner map is ' + oldPlanOwners);
            system.debug('----------new owner map is ' + newPlanOwners);
             reassignRelatedObjectiveRecords(oldPlanOwners, newPlanOwners);
        }
    }
    
    //This method will create the Objective plans when the Quick Action in the OT is hit.
    private void CreateRegplanObjectiveRecord(Map<Id, BI_Territory_Plan__c> mapNewdp) {
        
        //To Collect the Objective Category Ids into the set
        Set<Id> ObjectiveCategoryIds = new Set<Id>();
        //To Collect the Objective Type Ids into the set
        Set<Id> ObjectiveTypeIds = new Set<Id>();
        List<String> ObjYear = new List<String>();
        List<BI_Objectives__c> listBIsObjective = new List<BI_Objectives__c>();
        Set<String> uRegional = new Set<String>();
        Set<String> uDivision = new Set<String>();
        
        for (BI_Territory_Plan__c dp : mapNewdp.values()){
            if(dp.BI_Region__c !=null){
                ObjYear.add(dp.BI_Territory_Plan_Year__c);
                uRegional.add(dp.BI_Region__c);
                uDivision.add(dp.BI_Division__c);
            }
        }
        
        String newUDiv = String.valueOf(uDivision);
        newUDiv = newUDiv.replace('{', '');
        newUDiv = newUDiv.replace('}', '');
        
        String newUReg = String.valueOf(uRegional);
        newUReg = newUReg.replace('{', '');
        newUReg = newUReg.replace('}', '');
        //colelct eh objectives type record form the SOQL by passing the vlaues
        if(uRegional.size()>0){
            List<BI_Objective_Type__c> listobjtype = [Select Id,BI_Objective_Name__c,BI_Description__c, BI_Focus_Accounts__c,BI_Measure__c, BI_Target_Value__c, BI_Target_Date__c,BI_Objective_Category__c from BI_Objective_Type__c
                                                      where (BI_Region__c INCLUDES(:newUReg) 
                                                             OR BI_Division__c INCLUDES(:newUDiv))
                                                      AND BI_Active__c = :BI_UtilityCls.TRUEVALUE
                                                      AND BI_Auto_Create_Objective__c =:BI_UtilityCls.TRUEVALUE
                                                      AND BI_Relevant_Plans__c INCLUDES(:BI_UtilityCls.TERRITORYPLAN)
                                                      Limit 10000];
            //System.debug(LoggingLevel.INFO, '*** listobjtypelistobjtype: ' + listobjtype);                                                
            
            if(listobjtype.size()>0){  
                for(BI_Territory_Plan__c dp : mapNewdp.values()){
                    for(BI_Objective_Type__c objtype:listobjtype){
                        BI_Objectives__c biObj = new BI_Objectives__c();
                        biObj.RecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJACTIVES,BI_UtilityCls.TERRITORYOBJECTIVE);     
                        biObj.BI_Objective_Category__c = objtype.BI_Objective_Category__c;
                        biObj.BI_Objective_Type__c = objtype.Id;
                        biObj.BI_Territory_Plan__c = dp.Id;
                        biObj.Name = objtype.BI_Objective_Name__c + ' (' + dp.BI_Plan_Owner_Employee_Id__c + ', ' + dp.BI_Territory_Plan_Year__c + ')';
                        biObj.BI_Template_Description__c = objtype.BI_Description__c;
                        biObj.BI_Measure__c = objtype.BI_Measure__c;
                        biObj.BI_Target_Value__c = objtype.BI_Target_Value__c;
                        biObj.BI_End_Date__c = objtype.BI_Target_Date__c;
                        biObj.BI_Focus_Accounts__c = objtype.BI_Focus_Accounts__c;
                        biObj.BI_Auto_Created__c = true;
                        
                        //Adding all the new records into the list
                        listBIsObjective.add(biObj);
                    }
                }
                //check if the list is not empty else insert the records
                if(listBIsObjective.size()>0){
                    DataBase.insert(listBIsObjective,BI_UtilityCls.FALSEVALUE);
                }
            }
        }
    }
    
     private void reassignRelatedObjectiveRecords(Map < Id, Id > oldPlanOwners, Map < Id, Id > newPlanOwners) {
     
        List<BI_Objectives__c> updateObjList = new List<BI_Objectives__c>();
        List<BI_Territory_Plan__c> planList = new List<BI_Territory_Plan__c>([Select Id, OwnerId,BI_Plan_Owner_Employee_Id__c, BI_Territory_Plan_Year__c, (Select Id, Name, OwnerId, BI_Template_Objective_Name_From_Type__c From Objectives__r) 
                                                                                From BI_Territory_Plan__c Where Id in :oldPlanOwners.keyset()]);
        try {
            if(planList.size() > 0){
                for(BI_Territory_Plan__c pl : planList){
                    if(pl.Objectives__r != null){
                        for(BI_Objectives__c obj : pl.Objectives__r){
                            obj.OwnerId = pl.OwnerId;
                            obj.Name = obj.BI_Template_Objective_Name_From_Type__c + ' (' + pl.BI_Plan_Owner_Employee_Id__c + ', ' + pl.BI_Territory_Plan_Year__c + ')';
                            updateObjList.add(obj);
                        }
                    }
                }
                
            } //end if
            
            if(updateObjList.size() > 0){
                update updateObjList;
            }
            
        } catch (Exception ex){
            system.debug('Error occurred in BI_Territory_Plan_Handler reassignRelatedObjectiveRecords method:  ' +ex);
        }

    }
    
}