_Source/force-app/main/default/objects/Case/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <formula>Account.Name</formula>
    <label>Account</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Auto_Notification_Closed__c.field-meta.xml
<CustomField>
    <fullName>BI_Auto_Notification_Closed__c</fullName>
    <defaultValue>If($RecordType.DeveloperName  = &apos;Post_Travel&apos; || $RecordType.DeveloperName  = &apos;Pre_Travel&apos;,
&apos;None&apos;,
If($RecordType.DeveloperName  = &apos;Product&apos;,
&apos;UA Employee &amp; Customer Contact&apos;,
If($RecordType.DeveloperName  = &apos;Business_Insight_Case&apos; || $RecordType.DeveloperName  = &apos;Business_Insight_Case_Release&apos;,
&apos;UA Employee (Internal Only)&apos;,
&apos;None&apos;
)
)
)</defaultValue>
    <label>Auto Notification - Closed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Do Not Send</fullName>
            </value>
            <value>
                <fullName>Customer Contact (External Only)</fullName>
            </value>
            <value>
                <fullName>UA Employee (Internal Only)</fullName>
            </value>
            <value>
                <fullName>UA Employee &amp; Customer Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Auto_Notification_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>BI_Auto_Notification_In_Progress__c</fullName>
    <defaultValue>If($RecordType.DeveloperName  = &apos;Post_Travel&apos; || $RecordType.DeveloperName  = &apos;Business_Insight_Case&apos; || $RecordType.DeveloperName  = &apos;Business_Insight_Case_Release&apos;,
&apos;UA Employee (Internal Only)&apos;,
If($RecordType.DeveloperName  = &apos;Pre_Travel&apos;,
&apos;None&apos;,
If($RecordType.DeveloperName  = &apos;Product&apos;,
&apos;UA Employee &amp; Customer Contact&apos;,
&apos;None&apos;
)
)
)</defaultValue>
    <label>Auto Notification - In Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Do Not Send</fullName>
            </value>
            <value>
                <fullName>UA Employee (Internal Only)</fullName>
            </value>
            <value>
                <fullName>Customer Contact (External Only)</fullName>
            </value>
            <value>
                <fullName>UA Employee &amp; Customer Contact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Close_Comments__c.field-meta.xml
<CustomField>
    <fullName>BI_Close_Comments__c</fullName>
    <label>Close Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Logged_By__c.field-meta.xml
<CustomField>
    <fullName>BI_Logged_By__c</fullName>
    <formula>if(ISBLANK(ContactId)  &amp;&amp; ISBLANK(BI_User__c) &amp;&amp; !ISBLANK(SuppliedName)  ,
SuppliedName,
if(ISBLANK(ContactId)  &amp;&amp; !ISBLANK(BI_User__c),
 BI_User__r.FirstName  &amp; &quot; &quot; &amp; BI_User__r.LastName,
if(!ISBLANK(ContactId)  &amp;&amp; ISBLANK(BI_User__c),
Contact.FirstName &amp; &quot; &quot; &amp; Contact.LastName ,
if(!ISBLANK(ContactId)  &amp;&amp; !ISBLANK(BI_User__c) &amp;&amp; !ISBLANK(SuppliedName),
SuppliedName,
if(!ISBLANK(ContactId)  &amp;&amp; !ISBLANK(BI_User__c) &amp;&amp; ISBLANK(SuppliedName),
Contact.FirstName &amp; &quot; &quot; &amp; Contact.LastName &amp; &quot; (UA:&quot; &amp; BI_User__r.FirstName &amp; &quot; &quot; &amp; BI_User__r.LastName &amp; &quot;)&quot;,
&quot;UNKNOWN&quot;
)
)
)
)
)</formula>
    <label>Logged By</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Owner__c.field-meta.xml
<CustomField>
    <fullName>BI_Owner__c</fullName>
    <formula>IF( ISBLANK(Owner:Queue.QueueName),  Owner:User.FirstName  &amp;  &apos; &apos; &amp;  Owner:User.LastName, Owner:Queue.QueueName )</formula>
    <label>Owner</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Planned_Release_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_Planned_Release_Date__c</fullName>
    <label>(Planned) Release Date</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Record_Type__c</fullName>
    <formula>RecordType.Name</formula>
    <label>Record Type</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Subject_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Subject_Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts and Contacts</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Amenities</fullName>
            </value>
            <value>
                <fullName>AO Support (Airport Support)</fullName>
            </value>
            <value>
                <fullName>Baggage – Delayed</fullName>
            </value>
            <value>
                <fullName>Baggage – General / Other</fullName>
            </value>
            <value>
                <fullName>Baggage – LOB (Lost on Board)</fullName>
            </value>
            <value>
                <fullName>Baggage – Prepaid</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Corporate Security</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Debit Memo</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>Jetstream Banking</fullName>
            </value>
            <value>
                <fullName>Login / Password</fullName>
            </value>
            <value>
                <fullName>Memberships</fullName>
            </value>
            <value>
                <fullName>MileagePlus</fullName>
            </value>
            <value>
                <fullName>Mobile Application</fullName>
            </value>
            <value>
                <fullName>NDC – Link</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outlook Synchronization</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>PNR – General / Other</fullName>
            </value>
            <value>
                <fullName>PNR – Seats</fullName>
            </value>
            <value>
                <fullName>PNR – Ticketing</fullName>
            </value>
            <value>
                <fullName>PNR – Upgrades</fullName>
            </value>
            <value>
                <fullName>Policy and Procedure</fullName>
            </value>
            <value>
                <fullName>Portal help</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/User/fields/BI_Cases_Queue_Membership__c.field-meta.xml
<CustomField>
    <fullName>BI_Cases_Queue_Membership__c</fullName>
    <label>Cases Queue Membership</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMEX Queue</fullName>
            </value>
            <value>
                <fullName>Beverage Coupons Queue</fullName>
            </value>
            <value>
                <fullName>BI Release Queue</fullName>
            </value>
            <value>
                <fullName>BI Support Queue</fullName>
            </value>
            <value>
                <fullName>Corporate Direct (UCD) Queue</fullName>
            </value>
            <value>
                <fullName>Corporate Reports Queue</fullName>
            </value>
            <value>
                <fullName>CSST Queue</fullName>
            </value>
            <value>
                <fullName>Entertainment Queue</fullName>
            </value>
            <value>
                <fullName>Feedback Queue</fullName>
            </value>
            <value>
                <fullName>Government Queue</fullName>
            </value>
            <value>
                <fullName>Meetings Queue</fullName>
            </value>
            <value>
                <fullName>PassPlus Queue</fullName>
            </value>
            <value>
                <fullName>Policy &amp; Procedure Queue</fullName>
            </value>
            <value>
                <fullName>Portal Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/classes/BI_LightningUtility_OwnerQueueCases.cls
/**************************************************************************************************
* Name           : BI_LightningUtility_OwnerQueueCases
* Object         : Case
* Refer          : Used as controller for lightning components a) BI_LightningUtility_QueueCases and b) BI_Lightning_Utility_OwnerCases
* Author         : Yolande Anjargholi
* Create Date    : 2020 - 03
* Modify History :
********************************************************************************************/

public class BI_LightningUtility_OwnerQueueCases {
    
     @AuraEnabled
    public static List<Object> getQueueCases(Integer LimitSize, List<String> recIdList, String Orderby, String OrderDir){
        Set<Id> IdSet = new Set<Id>();
        
        if(Orderby == 'linkname'){
            Orderby = 'CaseNumber';
        }        
                
        if(recIdList.size() > 0){
            IdSet = new Map<Id, Case>([Select Id From Case Where Id In : recIdList]).keySet();
        }
        
		Id userId = UserInfo.getUserId();        
        Set<String> QueueMemSet = new Set<String>();
        OrderDir = String.isBlank(OrderDir) ? 'desc' : OrderDir;
        
        for(User us : [Select BI_Cases_Queue_Membership__c From User Where Id = :userId Limit 1]){
            //QueueMemSet.add(us.BI_Cases_Queue_Membership__c);
             IF(!string.isBlank(us.BI_Cases_Queue_Membership__c)) QueueMemSet.addAll(us.BI_Cases_Queue_Membership__c.split(';')); 
        }
        String query = 'SELECT Id,CaseNumber, CreatedDate, Subject, BI_Subject_Category__c, Description, BI_Account__c, BI_Record_Type__c, BI_Logged_By__c, BI_Owner__c FROM Case Where BI_Owner__c in :QueueMemSet';
        
        if(IdSet.size() > 0){
            query += ' and Id NOT IN : IdSet ';
        }                
       
        query += ' ORDER BY '+Orderby+' '+ OrderDir;        
        
        if(LimitSize != null && Integer.valueOf(LimitSize) > 0){
            LimitSize = Integer.valueOf(LimitSize);
            query += ' Limit ' +LimitSize;             
        }        
        
       return Database.query(query);
    }
    
    @AuraEnabled
    public static List<Object> getOwnerCases(Integer LimitSize, List<String> recIdList, String Orderby, String OrderDir){
        Set<Id> IdSet = new Set<Id>();
        Id userId = UserInfo.getUserId();
        String excludedRecType = 'SIP Beverage Coupon';
        
        if(Orderby == 'linkname'){
            Orderby = 'CaseNumber';
        }
        
        if(recIdList.size() > 0){
            IdSet = new Map<Id, Case>([Select Id From Case Where Id In : recIdList]).keySet();
        }
        
        OrderDir = String.isBlank(OrderDir) ? 'desc' : OrderDir;
        
        String query = 'SELECT CaseNumber, CreatedDate, Subject, BI_Subject_Category__c,Description, BI_Account__c, BI_Record_Type__c, BI_Logged_By__c, Status, BI_Auto_Notification_In_Progress__c, BI_Auto_Notification_Closed__c, BI_Planned_Release_Date__c, BI_Close_Comments__c FROM Case Where BI_Record_Type__c != :excludedRecType and isClosed = false and ownerId = :userId';
        
        if(IdSet.size() > 0){
            query += ' and Id NOT IN : IdSet ';
        } 
        
        query += ' ORDER BY '+Orderby+' '+ OrderDir;
        
        if(LimitSize != null && Integer.valueOf(LimitSize) > 0){
            LimitSize = Integer.valueOf(LimitSize);
            query += ' Limit ' +LimitSize;            
        }
        system.debug('*****the query is ' +query);
        return Database.query(query);
    }
    
     @AuraEnabled
    public static boolean updateCases(List<Case> editedCaseList){
        try{
            update editedCaseList;
            return true;
        } catch(Exception e){
            system.debug('Error in BI_LightningUtility_OwnerCases - updateCases method ' + e);
            return false;
        }
    }
    
    @AuraEnabled
    public static boolean ownCases(List<String> myCaseList){
        try{
            Id userId = UserInfo.getUserId();
            List<Case> updateList = new List<Case>();
            
            For(Case ca : [Select Id, OwnerId From Case Where Id in :myCaseList]){
                ca.OwnerId = userId;
                updateList.add(ca);
            }
            update updateList;
            return true;
        } catch(Exception e){
            return false;
        }
    }
    
    @AuraEnabled
    public static String getCasesRecType(List<String> theCaseList, String selectedRowId){
        system.debug('the list is ' + theCaseList);
        string recType = '';
        string validType = '';
        String returnString = '';        
        List<String> returnList = new List<String>();
        
        For(Case c : [Select Id, Status, BI_Record_Type__c From Case Where Id in :theCaseList]){
            If(returnString == ''){
                returnString = c.BI_Record_Type__c;                
            } else {
                if(returnString != c.BI_Record_Type__c){
                returnString = 'invalid';  
                }            
            }
        }
         return returnString;
    }  



}