_Source/force-app/main/default/objects/Case/fields/BI_Subject_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Subject_Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accounts and Contacts</fullName>
            </value>
            <value>
                <fullName>Activities</fullName>
            </value>
            <value>
                <fullName>Amenities</fullName>
            </value>
            <value>
                <fullName>AO Support (Airport Support)</fullName>
            </value>
            <value>
                <fullName>Baggage – Delayed</fullName>
            </value>
            <value>
                <fullName>Baggage – General / Other</fullName>
            </value>
            <value>
                <fullName>Baggage – LOB (Lost on Board)</fullName>
            </value>
            <value>
                <fullName>Baggage – Prepaid</fullName>
            </value>
            <value>
                <fullName>Chatter</fullName>
            </value>
            <value>
                <fullName>Corporate Security</fullName>
            </value>
            <value>
                <fullName>Customer Care</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Debit Memo</fullName>
            </value>
            <value>
                <fullName>ER</fullName>
            </value>
            <value>
                <fullName>Jetstream Banking</fullName>
            </value>
            <value>
                <fullName>Login / Password</fullName>
            </value>
            <value>
                <fullName>Memberships</fullName>
            </value>
            <value>
                <fullName>MileagePlus</fullName>
            </value>
            <value>
                <fullName>Mobile Application</fullName>
            </value>
            <value>
                <fullName>NDC – Link</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outlook Synchronization</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>PNR – General / Other</fullName>
            </value>
            <value>
                <fullName>PNR – Seats</fullName>
            </value>
            <value>
                <fullName>PNR – Ticketing</fullName>
            </value>
            <value>
                <fullName>PNR – Upgrades</fullName>
            </value>
            <value>
                <fullName>Policy and Procedure</fullName>
            </value>
            <value>
                <fullName>Portal help</fullName>
            </value>
            <value>
                <fullName>Pricing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/Case/fields/BI_Vanity_Mailbox_Source__c.field-meta.xml
<CustomField>
    <fullName>BI_Vanity_Mailbox_Source__c</fullName>
    <description>If the case was submitted via Email-to-Case, this will be the Vanity mailbox that routed case. This field is populated via the BI_CaseTriggerHandler</description>
    <label>Vanity Mailbox Source</label>
    <type>TextArea</type>
</CustomField>

_Source/force-app/main/default/classes/BI_CasesInvokeAssignmentRules.cls
/**********************************************************************
Name:  BI_CasesInvokeAssignmentRules
======================================================
======================================================
Purpose:
-------
Invoke Case Assignment Rules after Case is updated via process builder
Currently Used in Process Builder Flow: tbd
======================================================
======================================================
History
-------
VERSION  AUTHOR                    DATE              DETAIL            
1.0     Yolande Anjargholi        2020 - 02          INITIAL DEVELOPMENT 
***********************************************************************/

public class BI_CasesInvokeAssignmentRules {

    @InvocableMethod
    
    public static void CaseAssign(List<Id> CaseIds)
    {
        
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule= true; 
        	dmo.EmailHeader.TriggerUserEmail = true;
            List<case> Cases = new List<case>([Select Id,BI_Vanity_Mailbox_Source__c,BI_Subject_Category__c From Case Where Id in : CaseIds]);
            For(case c : Cases){
                c.setOptions(dmo);
            }
            update Cases;
   }
}