_Source/force-app/main/default/objects/Account/fields/BI_Account_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>BI_Account_Type_ID__c</fullName>
    <formula>Case(RecordType.Name,
&apos;Corporate&apos;, &quot;Corp - &quot; &amp; SIP_Corp_UCS_ID__c,
&apos;Agency Branch&apos;, &quot;Branch - &quot; &amp; SIP_ARC_Number__c,
&apos;Agency HOL&apos;, &quot;HOL - &quot; &amp; SIP_ARC_Number__c, 
&apos;Membership Group&apos;,&quot;Mem Grp - &quot; &amp; Text(SIP_Membership_Type__c),
&apos;Membership Sub-Group&apos;, &quot;Mem Subgrp - &quot; &amp;   Parent.Name ,
&apos;Custom Account&apos;, 
Case(TEXT(BI_Account_Type__c),
&apos;Airline&apos;, &quot;Cust Acct (Airline)&quot;,
&apos;Airport&apos;, &quot;Cust Acct (Airpt)&quot;,
&apos;&apos;, &quot;Cust Acct (Gvt/Assoc/Other)&quot; ,
&apos;Perks Plus Account&apos;, &quot;Cust Acct (Perks) &quot; &amp; &quot; - &quot;&amp; &quot;PP ID: &quot; &amp; BI_Perks_Plus_ID__c,
&apos;Non-UCS Corporate Account&apos;, if(BI_LH_UCID__c &lt;&gt; &quot;&quot;, &quot;Cust Acct (Non-UCS Corp) - LH UCID: &quot; &amp;  BI_LH_UCID__c,&quot;Cust Acc (Non-UCS Corp)&quot;),
&quot;&quot;
),
RecordType.Name &amp; &quot; - [NOT SET / NA]&quot;
)</formula>
    <label>Account Type &amp; ID</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Account/fields/SIP_Active__c.field-meta.xml
<CustomField>
    <fullName>SIP_Active__c</fullName>
    <defaultValue>IF( OR($RecordType.Name = &quot;Corporate&quot;, $RecordType.Name = &quot;Custom&quot;), &quot;Active&quot;, &quot;&quot;)</defaultValue>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>InActive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency HOL</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Account_Plan__c/BI_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>BI_Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_Plan_Year__c</fullName>
    <defaultValue>Text( YEAR(Today()))</defaultValue>
    <label>Plan Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Focus_Account__c/BI_Focus_Account__c.object-meta.xml
<CustomObject>
    <label>Focus Account</label>
    <nameField>
        <displayFormat>FA-{000000}</displayFormat>
        <label>Focus Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Focus Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Focus_Account__c/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Focused Objectives for the Account</relationshipLabel>
    <relationshipName>BI_Focus_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Focus_Account__c/fields/BI_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>BI_Account_Plan__c</referenceTo>
    <relationshipLabel>Focus Records</relationshipLabel>
    <relationshipName>BI_Focus_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Focus_Account__c/fields/BI_Objective__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective__c</fullName>
    <label>Objective</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You must select an objective that supports Focus Accounts. To determine if an objective support focus account records, navigate to your objective and look for the Focus Account section. If it is not visible, Focus Accounts are not supported.</errorMessage>
        <filterItems>
            <field>BI_Objectives__c.BI_Focus_Accounts__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objectives__c</referenceTo>
    <relationshipLabel>Focus Accounts</relationshipLabel>
    <relationshipName>BI_Focus_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Focus_Account__c/fields/BI_Objective_Strategy__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Strategy__c</fullName>
    <label>Objective Strategy &amp; Action Plan for Acc</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/BI_Objectives__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>BI_Account_Plan__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_Plan_Year__c</fullName>
    <description>This field is set pro grammatically via BI_PushAccountObjectives class to populate the plan year of the existing plan that the objective is linked to, so that it can be used to to auto link the objective to an account, since the formula field for Related Plan&apos;s Plan Year won&apos;t be populated on the before Insert event, yet.</description>
    <label>Plan Year</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_RelatedPlan_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_RelatedPlan_Plan_Year__c</fullName>
    <formula>IF(!ISBLANK(BI_Territory_Plan__c), 
TEXT(BI_Territory_Plan__r.BI_Territory_Plan_Year__c), 

IF(!ISBLANK(BI_Regional_Plan__c), 
TEXT(BI_Regional_Plan__r.BI_Regional_Plan_Year__c), 



if(!ISBLANK(BI_Divisional_Plan__c), 
TEXT(BI_Divisional_Plan__r.BI_Divisional_Plan_Year__c), 
&apos;&apos;)

)

)</formula>
    <label>Related Plan&apos;s Plan Year</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/classes/BI_ObjectiveEnhancements.cls
/**********************************************************************
Purpose:
-------
   Contains methods used by Custom Lightning Component Bundle: BI_Objective_Enhancement_FocusAccounts
   1. fetchFocusRecords - returns existing focus records for the objective
   2. fetchAccounts - returns active corp, agency and membership accounts
                      > that don't already have focus records
                      > that belong to the objective owner
   3. createFocusCustomerRecords - creates focus account records for the selected accounts
								   > will auto create account plan for account if one does not exist 
                                   > will auto link account plan if an existing one is found
   4. createAccountPlans - invoked by the createFocusCustomerRecords to create accounts plans
                           for focus records to be created where the selected account does not have an
                           existing plan
History
-------
  VERSION       AUTHOR                   DATE                DETAIL                  
   1.0          YOLANDE ANJ	             2019 - 11           Initial Development
*************************************************************************/

public class BI_ObjectiveEnhancements {
    
    
    //Get and Retrun the Existing Focus Records
    @AuraEnabled
    public static List<BI_Focus_Account__c> fetchFocusRecords(Id recordId ,String sortField, boolean isAsc) {
        
        String soql = '';
        soql = 'Select Name, BI_Account__r.Name, BI_Objective_Strategy__c FROM BI_Focus_Account__c WHERE BI_Objective__c = :recordId';
        
        if (sortField != '') {
            soql += ' order by ' + sortField;
            if (isAsc) {
                soql += ' asc';
            } else {
                soql += ' desc';
            }
        }
        system.debug('************ fetching focus records query will be ' + soql);
        
        try {     
            List<BI_Focus_Account__c> returnFocusList; 
            returnFocusList = Database.Query(soql);
            if (returnFocusList.size() > 0){
                return returnFocusList;
            } else {
                return null;
            }
            
        }  catch (Exception c){
            return null;
        }
        
    } //end method
    
    
    //Get and Retrun th Accounts
    @AuraEnabled
    public static List<Account> fetchAccounts(Id recordId ,String sortField, boolean isAsc, string showSalesTeamAccounts) {
        system.debug('***** include sales team val is ' +showSalesTeamAccounts);
        String soql = '';
        List<Account> listAccounts = new List<Account>();
        
        //create a set of account ids that already have a focus record for the objective so that we exclude them from the displayed list
        Set<ID> existingFocusAccIds = new Set<Id>();       
        For(BI_Focus_Account__c fc : [Select BI_Account__c FROM BI_Focus_Account__c WHERE BI_Objective__c = :recordId ]){
            existingFocusAccIds.add(fc.BI_Account__c);
        }
        
        //get the objective owner id **bulkify** so that we can get the owners account records
        Set<Id> ownerids = new Set<Id>();		
        for(BI_Objectives__c ob: [Select OwnerId From BI_Objectives__c Where Id =: recordId]){
            ownerids.add(ob.OwnerId);
        }
        
        Set<String> recordTypes = new Set<String>{'Corporate', 'Agency HOL', 'Agency Branch', 'Custom Account', 'Membership Group', 'Membership Sub-Group'};
              
        //SOQL Dynamic to pass the caluses
        soql = 'Select Id,Name,Owner.Name,OwnerId,BI_Account_Type_ID__c,BillingCity FROM Account WHERE SIP_Active__c != \'InActive\' AND RecordType.Name In :recordTypes AND OwnerId IN :ownerids AND Id NOT IN :existingFocusAccIds';
        
        //get Sales Team Accounts
        if(showSalesTeamAccounts == 'true'){
            Set<Id> teamAccountIdSet = new Map<Id, Account>([Select Id From Account Where Id in (Select accountId from accountTeamMember where userId IN :ownerids) AND SIP_Active__c != 'InActive' AND Id NOT IN :existingFocusAccIds AND RecordType.Name In :recordTypes
                                                            ]).keySet();
            soql = 'Select Id,Name,Owner.Name,OwnerId,BI_Account_Type_ID__c,BillingCity FROM Account WHERE RecordType.Name In :recordTypes AND Id NOT IN :existingFocusAccIds AND (OwnerId IN :ownerids OR Id IN :teamAccountIdSet)';
        
        }
        
        
        if (sortField != '') {
            soql += ' order by ' + sortField;
            if (isAsc) {
                soql += ' asc';
            } else {
                soql += ' desc';
            }
        }
        
        list <Account> lstResult;
        try {
            //--listAccount = Database.Query(soql);
            lstResult = Database.Query(soql);
            //System.debug(LoggingLevel.INFO, '*** lstResult: ' + lstResult);
            List <Account> returnAccountList = new List <Account> ();
            
            for (Account acc : lstResult){
                returnAccountList.add(acc);
            }
            return returnAccountList;
            
        }
        catch (Exception c){
            return null;
        }
        
        
    } //end method
    
    @AuraEnabled
    public static BI_Result createFocusCustomerRecords(string objectiveId, List<Id> AccountIdList){
        //check if focus record exist for obj - customer
        //if not create it
        BI_Result ret = new BI_Result();
        String objOwnerId = '';
        String Year = '';
        List<BI_Focus_Account__c> toInsertFocusRecords = new List<BI_Focus_Account__c>();
        List<BI_Focus_Account__c> toCreatePlanFocusRecords = new List<BI_Focus_Account__c>();
        List<String> insertedFocusRecords = new List<String>();
        
        
        try{
            if(AccountIdList.size() > 0 && objectiveId != null){
                
                //get objective record
                system.debug('****** in handler if');
                for(BI_Objectives__c obj : [Select Id, Name, OwnerId, BI_RelatedPlan_Plan_Year__c From BI_Objectives__c WHERE Id = :objectiveId limit 1]){
                    objOwnerId = obj.OwnerId;
                    Year = obj.BI_RelatedPlan_Plan_Year__c;
                }
                
                Map<ID, Id> mapAccountIdwithAccountPlanId = new Map<ID, Id>();
                Map<ID, Id> mapAccountIdwithNewAccountPlanId = new Map<ID, Id>();
                
                for(BI_Account_Plan__c accPlan : [SELECT Id, BI_Account__c FROM BI_Account_Plan__c 
                                                  WHERE BI_Plan_Year__c = :Year 
                                                  AND OwnerId = :objOwnerId 
                                                  AND BI_Account__c IN :AccountIdList]){
                                                      mapAccountIdwithAccountPlanId.put(accPlan.BI_Account__c, accPlan.Id);
                                                  }
                
                system.debug('*********************** map populated is ' + mapAccountIdwithAccountPlanId);
                
                
                for(Id AccId : AccountIdList){
                    
                    Id planId = null;
                    
                    if(mapAccountIdwithAccountPlanId.containsKey(AccId)){
                        planId = mapAccountIdwithAccountPlanId.get(AccId);
                    }
                    system.debug('********** plan id if found is ' +planId);
                    system.debug('******* in loop for account - acc is ' +AccId);
                    
                    BI_Focus_Account__c fc = new BI_Focus_Account__c(
                        //OwnerId = objOwnerId,
                        BI_Objective__c = objectiveId,
                        BI_Account__c = AccId,
                        BI_Account_Plan__c = planId
                    );
                    toInsertFocusRecords.add(fc); 
                    //Get Focus Record Accounts with no plans
                    if(fc.BI_Account_Plan__c == null){
                        toCreatePlanFocusRecords.add(fc); 
                    }
                }
                
                //create the account plans for accounts / focus records with no plans                
                If(toCreatePlanFocusRecords.size() > 0){
                    mapAccountIdwithNewAccountPlanId = createAccountPlans(toCreatePlanFocusRecords, Year, objOwnerId);
                }
                
                //update the FR records with the plan ID of the newly created plans
                For(BI_Focus_Account__c newFCrec : toInsertFocusRecords){
                    if(mapAccountIdwithNewAccountPlanId.containsKey(newFCrec.BI_Account__c)){
                        newFCrec.BI_Account_Plan__c = mapAccountIdwithNewAccountPlanId.get(newFCrec.BI_Account__c);
                    }
                }
                
                system.debug('*******************************focus records created for insert ' + toInsertFocusRecords);
                
                if(toInsertFocusRecords.size() > 0){
                    Database.insert(toInsertFocusRecords, False);
                    ret.Result = True;                    
                }
                
                
            } else{
                ret.Result = False;
            }
            
        } catch (Exception e){
            ret.Result = False;
            ret.Errors.add(e.getMessage());
        }
        
        system.debug('the objective id is ' +objectiveId);
        system.debug('the accountlist is ' +AccountIdList);
        return ret;
    }//end method
    
    public static Map<Id, Id> createAccountPlans (List<BI_Focus_Account__c> fcsWithoutPlans, String Year, String OwnerId){
        
        Map<ID, Id> mapAccountIdwithnewPlanId = new Map<ID, Id>();
        List<BI_Account_Plan__c> newPlans = new List<BI_Account_Plan__c>();
        
        For(BI_Focus_Account__c noPlanFC : fcsWithoutPlans){
            ID accID = noPlanFC.BI_Account__c;
            Account acc = [Select Name, OwnerId,RecordType.Name From Account Where ID = :accID limit 1];
            String accName = acc.Name;
            String AccrecType = acc.RecordType.Name;
            String ownId = Ownerid;
            String accPlanrecTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJACCOUNTPLAN,BI_UtilityCls.AGENCYACCTPLANRECORDTYPE);  
            IF(AccrecType == BI_UtilityCls.ACCTCORPRECORDTYPE || AccrecType == 'Custom Account'){
                accPlanrecTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJACCOUNTPLAN,BI_UtilityCls.CORPACCTPLANRECORDTYPE);   
            }
            BI_Account_Plan__c pl = new BI_Account_Plan__c(
                Name = Year + ' - ' + accName,           
                OwnerId = ownId,
                BI_Account__c = noPlanFC.BI_Account__c,
                BI_Plan_Year__c = Year,
                RecordTypeId = accPlanrecTypeId
            );
            newPlans.add(pl); 
            
        }
        
        If(newPlans.size() > 0){
            insert newPlans;
            For(BI_Account_Plan__c prec : newPlans){
                mapAccountIdwithnewPlanId.Put(prec.BI_Account__c, prec.Id);
            }
        }
        
        return mapAccountIdwithnewPlanId;
        
    } 
}