_Source/force-app/main/default/objects/Account/fields/BI_Abbreviated_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>BI_Abbreviated_Account_Name__c</fullName>
    <inlineHelpText>If the &apos;Account Name&apos; field on its own is not sufficiently descriptive or unique, you can use this field to enter an Account Name that helps you to more easily reference and find the account. Limit 15 Characters.</inlineHelpText>
    <label>Abbreviated Account Name</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

_Source/force-app/main/default/objects/Account/fields/BI_LH_UCID__c.field-meta.xml
<CustomField>
    <fullName>BI_LH_UCID__c</fullName>
    <label>LH Base UCID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Account/fields/BI_NH_Corporate_Code__c.field-meta.xml
<CustomField>
    <fullName>BI_NH_Corporate_Code__c</fullName>
    <label>NH Corporate Code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Account/fields/SIP_ARC_Number__c.field-meta.xml
<CustomField>
    <fullName>SIP_ARC_Number__c</fullName>
    <externalId>true</externalId>
    <label>ARC / IATA#</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

_Source/force-app/main/default/objects/Account/fields/SIP_Corp_UCS_ID__c.field-meta.xml
<CustomField>
    <fullName>SIP_Corp_UCS_ID__c</fullName>
    <externalId>true</externalId>
    <label>Corp UCS ID</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/BI_Territory_Plan__c.object-meta.xml
<CustomObject>
    <label>Territory Plan</label>
    <nameField>
        <label>Territory Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/classes/BI_TerritoryPlanWithAccountAndObjective.cls
/**************************************************************************

Name : BI_TerritoryPlanWithAccountAndObjective 

===========================================================================
Purpose : This class is used for showing Objective realted to Account in the Territory Plan
===========================================================================
History:
--------
VERSION    AUTHOR         DATE           DETAIL          DESCRIPTION
1.0        Lester         31/May/2017     Created 
***************************************************************************/
public with sharing class BI_TerritoryPlanWithAccountAndObjective {

	//This method will get the objective list records to pass in the UI
	@AuraEnabled
	public static List<Account> getObjectivesList(Id recordId ,Boolean initflag, String sortField, boolean isAsc) {
		List<Account> listAccount = new List<Account>();
		List<BI_Territory_Plan__c> terrPlan = [Select OwnerId From BI_Territory_Plan__c Where Id =: recordId limit 1];
	    String soql = '';

	    //System.debug(LoggingLevel.INFO, '*** terrPlan: ' + terrPlan);
		Set<Id> ownerids = new Set<Id>();
		if(terrPlan.size()>0){
			for(BI_Territory_Plan__c tp: terrPlan){
				ownerids.add(tp.OwnerId);
			}
		}
		//SOQL Dynamic to pass the caluses
		soql = 'Select Id,Name,Owner.Name,Phone,BillingCity,BI_Abbreviated_Account_Name__c,SIP_ARC_Number__c,BI_NH_Corporate_Code__c,BI_LH_UCID__c,SIP_Corp_UCS_ID__c,RecordType.Name FROM Account WHERE OwnerId IN';
		soql +=':ownerids';		
		//soql += ' order by Name, RecordType.Name ASC';

        
        if (sortField != '') {
         soql += ' order by ' + sortField;
         if (isAsc) {
            soql += ' asc';
         } else {
            soql += ' desc';
         }
      }
		
       //soql += 'Limit 20';
        //set record limit
        if(initflag == true){
			soql=soql + ' limit 25';
		} else {
			soql=soql + ' limit 10000';
		 
		}
        
		//System.debug(LoggingLevel.INFO, '*** : soql' + soql);
		//--listAccount = Database.Query(soql);
		//--return listAccount;
        
        list <Account> lstResult;
        try {
            //--listAccount = Database.Query(soql);
            lstResult = Database.Query(soql);
            //System.debug(LoggingLevel.INFO, '*** lstResult: ' + lstResult);
            List <Account> returnAccList = new List <Account> ();
            
            for (account a : lstResult){
                returnAccList.add(a);
            }
            return returnAccList;
        }
        catch (Exception c){
            return null;
        }
        
        
	} //end method

} //end class