_Source/force-app/main/default/objects/Account/fields/BI_Account_Type_ID__c.field-meta.xml
<CustomField>
    <fullName>BI_Account_Type_ID__c</fullName>
    <formula>Case(RecordType.Name,
&apos;Corporate&apos;, &quot;Corp - &quot; &amp; SIP_Corp_UCS_ID__c,
&apos;Agency Branch&apos;, &quot;Branch - &quot; &amp; SIP_ARC_Number__c,
&apos;Agency HOL&apos;, &quot;HOL - &quot; &amp; SIP_ARC_Number__c, 
&apos;Membership Group&apos;,&quot;Mem Grp - &quot; &amp; Text(SIP_Membership_Type__c),
&apos;Membership Sub-Group&apos;, &quot;Mem Subgrp - &quot; &amp;   Parent.Name ,
&apos;Custom Account&apos;, 
Case(TEXT(BI_Account_Type__c),
&apos;Airline&apos;, &quot;Cust Acct (Airline)&quot;,
&apos;Airport&apos;, &quot;Cust Acct (Airpt)&quot;,
&apos;&apos;, &quot;Cust Acct (Gvt/Assoc/Other)&quot; ,
&apos;Perks Plus Account&apos;, &quot;Cust Acct (Perks) &quot; &amp; &quot; - &quot;&amp; &quot;PP ID: &quot; &amp; BI_Perks_Plus_ID__c,
&apos;Non-UCS Corporate Account&apos;, if(BI_LH_UCID__c &lt;&gt; &quot;&quot;, &quot;Cust Acct (Non-UCS Corp) - LH UCID: &quot; &amp;  BI_LH_UCID__c,&quot;Cust Acc (Non-UCS Corp)&quot;),
&quot;&quot;
),
RecordType.Name &amp; &quot; - [NOT SET / NA]&quot;
)</formula>
    <label>Account Type &amp; ID</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/BI_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>BI_Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_ManagerRSD_Review_Completed_On__c.field-meta.xml
<CustomField>
    <fullName>BI_ManagerRSD_Review_Completed_On__c</fullName>
    <label>Manager / RSD Review Completed On</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_Plan_Year__c</fullName>
    <defaultValue>Text( YEAR(Today()))</defaultValue>
    <label>Plan Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_RSDMD_Review_Completed_On__c.field-meta.xml
<CustomField>
    <fullName>BI_RSDMD_Review_Completed_On__c</fullName>
    <label>RSD/MD Review Completed On</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/BI_Territory_Plan__c.object-meta.xml
<CustomObject>
    <label>Territory Plan</label>
    <nameField>
        <label>Territory Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/fields/BI_Territory_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_Territory_Plan_Year__c</fullName>
    <label>Plan Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/classes/BI_TerritoryPlanWithAccountPlans.cls
public with sharing class BI_TerritoryPlanWithAccountPlans {

	//This method will get the account plan list records to pass in to the lightning component UI
	@AuraEnabled
	public static List<BI_Account_Plan__c> getAccountPlanList(Id recordId ,Boolean initflag, String sortField, boolean isAsc) {
		
		List<BI_Account_Plan__c> listAccountPlans = new List<BI_Account_Plan__c>();
		
        List<BI_Territory_Plan__c> terrPlan = [Select Id, OwnerId, BI_Territory_Plan_Year__c From BI_Territory_Plan__c Where Id =: recordId limit 1];
	    String soql = '';

	    //System.debug(LoggingLevel.INFO, '*** terrPlan: ' + terrPlan);
		Set<Id> ownerids = new Set<Id>();
		Set<String> planYears = new Set<String>();
        
        if(terrPlan.size()>0){
			for(BI_Territory_Plan__c tp: terrPlan){
				ownerids.add(tp.OwnerId);
                planYears.add(tp.BI_Territory_Plan_Year__c);
			}
		}
		

        
        //SOQL Dynamic to pass the caluses
		soql = 'Select Id,Name,Owner.Name,BI_Account__c,BI_Plan_Year__c, RecordType.Name, BI_Account__r.BI_Account_Type_ID__c, BI_ManagerRSD_Review_Completed_On__c, BI_RSDMD_Review_Completed_On__c FROM BI_Account_Plan__c WHERE OwnerId IN';
		soql +=':ownerids' + ' ';
        soql +='AND BI_Plan_Year__c IN' + ' ';
        soql +=':planYears';
		//soql += ' order by Name, RecordType.Name ASC';

        
        if (sortField != '') {
         soql += ' order by ' + sortField;
         if (isAsc) {
            soql += ' asc';
         } else {
            soql += ' desc';
         }
      }
		
       //soql += 'Limit 20';
        //set record limit
        if(initflag == true){
			soql=soql + ' limit 25';
		} else {
			soql=soql + ' limit 10000';
		 
		}

        
        list <BI_Account_Plan__c> lstResult;
        try {
            //--listAccount = Database.Query(soql);
            lstResult = Database.Query(soql);
            //System.debug(LoggingLevel.INFO, '*** lstResult: ' + lstResult);
            List <BI_Account_Plan__c> returnAccPlanList = new List <BI_Account_Plan__c> ();
            
            for (BI_Account_Plan__c accPlan : lstResult){
                returnAccPlanList.add(accPlan);
            }
            return returnAccPlanList;
           
        }
        catch (Exception c){
            return null;
        }
        
        
	} //end method

} //end class