_Source/force-app/main/default/objects/Account/fields/BI_Description__c.field-meta.xml
<CustomField>
    <fullName>BI_Description__c</fullName>
    <description>We are using this field to populate the business description from Hoovers, in the same way as the out of box description field. We added this custom field so that we can map the description from the lead custom description when the lead is converted and an existing account is selected, since we only have the option to map custom fields.</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

_Source/force-app/main/default/objects/Account/fields/BI_End_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/BI_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plans</relationshipLabel>
    <relationshipName>BI_Account_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Divisional_Plan__c/BI_Divisional_Plan__c.object-meta.xml
<CustomObject>
    <label>Divisional Plan</label>
    <nameField>
        <label>Divisional Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisional Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Category__c/BI_Objective_Category__c.object-meta.xml
<CustomObject>
    <label>Objective Category</label>
    <nameField>
        <label>Objective Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Type__c/BI_Objective_Type__c.object-meta.xml
<CustomObject>
    <label>Objective Type</label>
    <nameField>
        <label>Objective Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Description__c.field-meta.xml
<CustomField>
    <fullName>BI_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Measure__c.field-meta.xml
<CustomField>
    <fullName>BI_Measure__c</fullName>
    <label>Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Objective_Measure</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Objective_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Objective Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>BI_Objective_Category__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Category__c</referenceTo>
    <relationshipLabel>Objective Types</relationshipLabel>
    <relationshipName>Objective_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Name__c</fullName>
    <label>Objective Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Target_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_Target_Date__c</fullName>
    <label>Target Date</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Target_Value__c.field-meta.xml
<CustomField>
    <fullName>BI_Target_Value__c</fullName>
    <label>Target Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/BI_Objectives__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Account__c.field-meta.xml
<CustomField>
    <fullName>BI_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>BI_Account_Plan__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Auto_Created__c.field-meta.xml
<CustomField>
    <fullName>BI_Auto_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Created</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Divisional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Divisional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divisional Plan</label>
    <referenceTo>BI_Divisional_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_End_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_End_Date__c</fullName>
    <label>Target Date (if known &amp; applicable)</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Focus_Accounts__c.field-meta.xml
<CustomField>
    <fullName>BI_Focus_Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Focus Accounts</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BI_Objective_Category__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Category__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Owner_Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Owner_Employee_Id__c</fullName>
    <formula>Owner:User.Employee_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Objective Owner Employee Id</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Type</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (((2 AND 3) OR (4 AND 5) OR (6 AND 7)) OR 8 OR 9 OR 10)</booleanFilter>
        <errorMessage>The selected Objective Type is not valid for the type of Plan you are creating this Objective On</errorMessage>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Territory Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Territory Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Regional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Regional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Divisional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Divisional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>notContain</operation>
            <value>Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Account Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Description__c</field>
            <operation>equals</operation>
            <value>(2019)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Type__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Regional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Regional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Plan</label>
    <referenceTo>BI_Regional_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_RelatedPlan_Plan_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_RelatedPlan_Plan_Year__c</fullName>
    <formula>IF(!ISBLANK(BI_Territory_Plan__c), 
TEXT(BI_Territory_Plan__r.BI_Territory_Plan_Year__c), 

IF(!ISBLANK(BI_Regional_Plan__c), 
TEXT(BI_Regional_Plan__r.BI_Regional_Plan_Year__c), 



if(!ISBLANK(BI_Divisional_Plan__c), 
TEXT(BI_Divisional_Plan__r.BI_Divisional_Plan_Year__c), 
&apos;&apos;)

)

)</formula>
    <label>Related Plan&apos;s Plan Year</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Template_Description__c.field-meta.xml
<CustomField>
    <fullName>BI_Template_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Territory_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Territory_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Plan</label>
    <referenceTo>BI_Territory_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/BI_Regional_Plan__c.object-meta.xml
<CustomObject>
    <label>Regional Plan</label>
    <nameField>
        <label>Regional Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regional Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/fields/BI_Divisional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Divisional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divisional Plan</label>
    <referenceTo>BI_Divisional_Plan__c</referenceTo>
    <relationshipLabel>Regional Plans</relationshipLabel>
    <relationshipName>Regional_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/BI_Territory_Plan__c.object-meta.xml
<CustomObject>
    <label>Territory Plan</label>
    <nameField>
        <label>Territory Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/fields/BI_Regional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Regional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Plan</label>
    <referenceTo>BI_Regional_Plan__c</referenceTo>
    <relationshipLabel>Territory Plans</relationshipLabel>
    <relationshipName>Territory_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/classes/BI_ObjectiveHandler.cls
/**********************************************************************
Purpose:
-------
Deal with the DML for Objective

History
-------
VERSION  AUTHOR            DATE              DETAIL                              Description
1.0     Sasi Naik        22/05/2017          INITIAL DEVELOPMENT                 CSR:
2.0     Yolande Anjar    2019-11             Sales Planning Enhancement          Functionality to auto populate fields from type template when obj is manually created
***********************************************************************/
public class BI_ObjectiveHandler implements SIP_Triggers.Handler{
    public List<BI_Objectives__c> Newobj;
    public List<BI_Objectives__c> Oldobj;
    public Map<Id, BI_Objectives__c> mapNewobj;
    public Map<Id, BI_Objectives__c> mapOldobj;
    public Set<Id> objTypeIDSet;
    //New Objective List to collect the inserted objective records.
    List<BI_Objectives__c> newinsertobjectivelist = new List<BI_Objectives__c>();
    
    //New Objective List to collect the updated objective records.
    List<BI_Objectives__c> newupdateobjectivelist = new List<BI_Objectives__c>();
    
    //This method will initiate the trigger on which event the method need to call
    public void handle() {
        
        if(Trigger.isInsert) {
            Newobj = (List<BI_Objectives__c>)Trigger.new;
            //mapNewobj = (Map<Id, BI_Objectives__c>)Trigger.newMap;
        } else if (Trigger.isUpdate) {
            Newobj = (List<BI_Objectives__c>)Trigger.new;
            mapNewobj = (Map<Id, BI_Objectives__c>)Trigger.newMap;
        } 
        
        if(Trigger.isInsert && Trigger.isBefore) {
            System.debug(LoggingLevel.INFO, '*** Newobj: ' + Newobj);
            
            for (BI_Objectives__c obj : Newobj){
                newinsertobjectivelist.add(obj);  
            }
            
            if(newinsertobjectivelist.size()>0){
                ValidateDuplication(newinsertobjectivelist,false);
                AutoPopulateFromTypeTemplate(newinsertobjectivelist);
            }
        }
        
        if(Trigger.isUpdate && Trigger.isBefore) {
            System.debug(LoggingLevel.INFO, '*** Newobj: ' + Newobj);
            
            for (BI_Objectives__c obj : mapNewobj.values()){
                newupdateobjectivelist.add(obj);                    
            }
            
            if(newupdateobjectivelist.size()>0){
                ValidateDuplication(newupdateobjectivelist,true);
            } 
        } 
    }
    

    /*
* Purpose : To auto populate objective fields if the objective is manually created by the user
*/
    private static void AutoPopulateFromTypeTemplate(List<BI_Objectives__c> Newobj) {
        system.debug('************* in auto pop method');
        Set<Id> objTypeIds = new Set<Id>();
        List<BI_Objectives__c> obsUpdateList = new List<BI_Objectives__c>();
        Map <Id, BI_Objective_Type__c> planIdTypemap = new Map<Id, BI_Objective_Type__c>();
        
        For(BI_Objectives__c ob : Newobj){
            If(ob.BI_Auto_Created__c == false & ob.BI_Objective_Type__c != null){
                objTypeIds.add(ob.BI_Objective_Type__c);
                obsUpdateList.add(ob);
            }
        }
        
        
        If(obsUpdateList.size() > 0){
            List<BI_Objective_Type__c> obTyperecs = new List<BI_Objective_Type__c>([Select Id, Name, BI_Objective_Name__c, BI_Description__c, BI_Measure__c,
                                                                                    BI_Target_Value__c, BI_Target_Date__c, BI_Focus_Accounts__c From BI_Objective_Type__c 
                                                                                    Where ID IN :objTypeIds]);   
            
            For(BI_Objectives__c ob : obsUpdateList){
                For(BI_Objective_Type__c obtype : obTyperecs) {
                    If(ob.BI_Objective_Type__c == obtype.Id){
                        planIdTypemap.put(ob.Id, obtype);                  
                    }
                }             
            }
            
            For(BI_Objectives__c ob : obsUpdateList){
                BI_Objective_Type__c obTyp = planIdTypemap.get(ob.Id);
                ob.Name = obTyp.BI_Objective_Name__c + ' (' + ob.BI_Objective_Owner_Employee_Id__c + ', ' + ob.BI_RelatedPlan_Plan_Year__c + ')';  
                ob.BI_Template_Description__c = obTyp.BI_Description__c;
                ob.BI_Focus_Accounts__c = obTyp.BI_Focus_Accounts__c;
                ob.BI_Measure__c = obTyp.BI_Measure__c;
                ob.BI_Target_Value__c = obTyp.BI_Target_Value__c;
                ob.BI_End_Date__c = obTyp.BI_Target_Date__c;
            }

        }   
        
    }
    
    /*
* Purpose : To Validate the Duplicate Records not to enter into the Objectives Object
*/
    
    private static void ValidateDuplication(List<BI_Objectives__c> Newobj,boolean oflag) {
        system.debug('********* in validate duplication - new objectives inserted or updated ' + Newobj);
        //To Collect the Objective Category Ids into the set
        Set<Id> ObjectiveCategoryIds = new Set<Id>();
        //To Collect the Objaective Type Ids into the set
        Set<Id> ObjectiveTypeIds = new Set<Id>();
        //To Collect the Divisional Plan Ids into the set
        Set<Id> Divisionalplansids = new Set<Id>();
        //To Collect the Territory Plan Ids into the set
        Set<Id> Territoryplansids = new Set<Id>();	
        //To Collect the Regional Plan Ids into the set
        Set<Id> Regionalplansids = new Set<Id>();
        // //To Collect the Account Plan Ids into the set
        // Set<Id> Accountplansids = new Set<Id>();
        
        Set<Id> Objectivesids = new Set<Id>();
        // To Collect the List of Objectives
        List<BI_Objectives__c> listBIsObjective = new List<BI_Objectives__c>();
        
        //For loop to collect the objectives records values into the set and list 
        for (BI_Objectives__c obj : Newobj){
            ObjectiveCategoryIds.add(obj.BI_Objective_Category__c);
            ObjectiveTypeIds.add(obj.BI_Objective_Type__c);
            if(obj.BI_Divisional_Plan__c !=null){
                Divisionalplansids.add(obj.BI_Divisional_Plan__c);
            }
            if(obj.BI_Territory_Plan__c !=null){
                Territoryplansids.add(obj.BI_Territory_Plan__c);
            }
            if(obj.BI_Regional_Plan__c !=null){
                Regionalplansids.add(obj.BI_Regional_Plan__c);
            }
            //Accountplansids.add(obj.BI_Account_Plan__c);
            if(obj.Id != null){
                Objectivesids.add(obj.Id);
            }
        }
        
        System.debug(LoggingLevel.DEBUG, '*** : ComeToValidatation' );
        
        //Checking the Objecitveids has the value into the set then only we are process to do the other operation. 
        //if(Objectivesids.size()>0){
        listBIsObjective = [ Select Id,
                            Name,
                            BI_Objective_Category__c,
                            BI_Objective_Type__c,
                            BI_Divisional_Plan__c,
                            BI_Territory_Plan__c ,
                            BI_Regional_Plan__c,
                            BI_Account__c
                            FROM BI_Objectives__c 
                            WHERE BI_Objective_Category__c IN:ObjectiveCategoryIds 
                            AND BI_Objective_Type__c IN:ObjectiveTypeIds
                            //AND Id NOT IN:Objectivesids
                            AND (BI_Divisional_Plan__c IN:Divisionalplansids
                                 OR BI_Territory_Plan__c IN:Territoryplansids
                                 OR BI_Regional_Plan__c IN:Regionalplansids)
                            //OR BI_Account_Plan__c IN:Accountplansids)
                            Limit 10000];
        // }    
        
        
        System.debug(LoggingLevel.DEBUG, '********** existing objectives found : listBIsObjective' + listBIsObjective);
        //Checking the listBIsObjective has the value into the list then only we are process to do the other operation.      
        if(listBIsObjective.size()>0){
            system.debug('YYYY the oflag is ' + oflag);
            for(BI_Objectives__c obj : Newobj){
                system.debug('1a *************** now evaluating new objective: ' + obj + 'with type' + obj.BI_Objective_Type__c + 'and category ' + obj.BI_Objective_Category__c +  'for: ');
                system.debug('          1b*** NEW OBJ PLAN IS ' + obj.BI_Territory_Plan__c);
                for(BI_Objectives__c oldobj : listBIsObjective){
                    system.debug('                     2a---------existing objective found ' + oldobj + ' type is ' + oldobj.BI_Objective_Type__c + ' cat is ' + oldobj.BI_Objective_Category__c);
                    system.debug('                             2b  -- existing obj found plan is ' + oldobj.BI_Territory_Plan__c);
                    // check the condition when the record is getting inserted
                    if(!oflag){
                        system.debug('+++ ready for if to compare ids which are NEW: ' + obj.BI_Territory_Plan__c + ' OLD: ' + oldobj.BI_Territory_Plan__c);
                        if(obj.BI_Divisional_Plan__c == oldobj.BI_Divisional_Plan__c &&  obj.BI_Divisional_Plan__c != BI_UtilityCls.NULLVALUE){
                            obj.addError(System.Label.BI_ObjectiveDivisionDuplicateErrorMSG); 
                        } else if(obj.BI_Regional_Plan__c == oldobj.BI_Regional_Plan__c &&  obj.BI_Regional_Plan__c != BI_UtilityCls.NULLVALUE){
                            obj.addError(System.Label.BI_ObjectiveRegionalDuplicateErrorMSG); 
                        } else if(obj.BI_Territory_Plan__c == oldobj.BI_Territory_Plan__c &&  obj.BI_Territory_Plan__c != BI_UtilityCls.NULLVALUE){
                            obj.addError(System.Label.BI_ObjectiveTerritoryDuplicateErrorMSG); 
                        } 
                    }
                    
                    // check the condition when the record is getting Updated
                    if(oflag){
                        system.debug('+++== ready for if to compare ids which are NEW: ' + obj.BI_Territory_Plan__c + ' OLD: ' + oldobj.BI_Territory_Plan__c);
                        system.debug('=== objective ids include ' + Objectivesids);
                        system.debug('#### and it should not contain ' + obj.Id);
                        if(obj.BI_Divisional_Plan__c == oldobj.BI_Divisional_Plan__c && obj.BI_Divisional_Plan__c != BI_UtilityCls.NULLVALUE && !Objectivesids.contains(obj.Id)){
                            obj.addError(System.Label.BI_ObjectiveDivisionDuplicateErrorMSG); 
                        } else if(obj.BI_Regional_Plan__c == oldobj.BI_Regional_Plan__c && obj.BI_Regional_Plan__c != BI_UtilityCls.NULLVALUE && !Objectivesids.contains(obj.Id)){
                            obj.addError(System.Label.BI_ObjectiveRegionalDuplicateErrorMSG); 
                        } else if(obj.BI_Territory_Plan__c == oldobj.BI_Territory_Plan__c && obj.BI_Territory_Plan__c != BI_UtilityCls.NULLVALUE && !Objectivesids.contains(obj.Id)){
                            system.debug('EEEEEEEEEEk Sad face');
                            obj.addError(System.Label.BI_ObjectiveTerritoryDuplicateErrorMSG); 
                        } 
                    }
                }		
            } 	 
        }
        System.debug(LoggingLevel.DEBUG, '*** IsEnd: ');   
    }
    
    
}