_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/BI_Proposal_Request_Form__c.object-meta.xml
<CustomObject>
    <label>Proposal Request Form</label>
    <nameField>
        <displayFormat>PRF-{00000}</displayFormat>
        <label>Proposal Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Legal_Review_Required__c.field-meta.xml
<CustomField>
    <fullName>BI_Legal_Review_Required__c</fullName>
    <label>Legal Review Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>BI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Pricing_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Stage__c.field-meta.xml
<CustomField>
    <fullName>BI_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Proposal_Request_Form_Status</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/classes/BI_RemoteController.cls
/**********************************************************************
   Name:  BI_RemoteController
   ======================================================
   ======================================================
   Purpose:
   -------
   Deal with the DML for Objective ,price grid
   ======================================================
   ======================================================
   History
   -------
   VERSION  AUTHOR            DATE              DETAIL            Description
   1.0     Danni Xi        15/05/2017      INITIAL DEVELOPMENT          CSR:
 ***********************************************************************/
public with sharing class BI_RemoteController {
    /*
     * Method : Submit Proposal Request Form
     * Purpose : Submit Proposal Request Form
     * Params : String proposalRequestFormId   - ID of the object of pricing grid         
     */
    @AuraEnabled
    public static BI_Result submitProposalRequestForm(Id proposalRequestFormId) {
        //System.debug(LoggingLevel.DEBUG, '*** start ');
        BI_Result ret = new BI_Result();
        //System.debug(LoggingLevel.DEBUG, '*** ===proposalRequestFormId: ' + proposalRequestFormId);
        try {
      
            List < BI_Proposal_Request_Form__c > objs = [SELECT Id, 
                                                                BI_Stage__c,
                                                                BI_Legal_Review_Required__c,
                                                                BI_Opportunity__c,
                                                                RecordTypeId
                                                                FROM BI_Proposal_Request_Form__c
                                                                WHERE Id = : proposalRequestFormId
                                                                LIMIT 1
            ];
            //System.debug(LoggingLevel.DEBUG, '*** objs: ' + objs);
            if (objs.size() > 0) {
                BI_Proposal_Request_Form__c obj = objs[0];
                String Idstr = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJPRICINGREQUEST, BI_UtilityCls.PRICINGREQPASSPLUSRECORDTYPE);
                if (obj.BI_Stage__c == BI_UtilityCls.DRF_STAGE && obj.RecordTypeId != Idstr) {
                    obj.BI_Stage__c = BI_UtilityCls.SUBMIT;
                    database.update(obj);
                    ret.Result = obj.BI_Opportunity__c; 
                    // ret.Result = True;
                } else {
                    database.update(obj); // Do not remoove this line, in case cannot refresh value on page
                    
                    String errorMessage = '';
                    ret.Errors.add(errorMessage);
                }
            } else {
                String errorMessage = BI_UtilityCls.NOTVALIDPRF;
                ret.Errors.add(errorMessage);
            }

        } catch (Exception e) {
            ret.Errors.add(e.getMessage());
        }
        //System.debug(LoggingLevel.DEBUG, '*** ret===: ' + ret);
        return ret;
    }

}