_Source/force-app/main/default/objects/BI_Divisional_Plan__c/BI_Divisional_Plan__c.object-meta.xml
<CustomObject>
    <label>Divisional Plan</label>
    <nameField>
        <label>Divisional Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisional Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Divisional_Plan__c/fields/BI_Division__c.field-meta.xml
<CustomField>
    <fullName>BI_Division__c</fullName>
    <formula>TEXT(  Owner:User.BI_Objective_Division__c  )</formula>
    <label>Division</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Category__c/BI_Objective_Category__c.object-meta.xml
<CustomObject>
    <label>Objective Category</label>
    <nameField>
        <label>Objective Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Categories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Category__c/fields/BI_Active__c.field-meta.xml
<CustomField>
    <fullName>BI_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/BI_Objective_Type__c.object-meta.xml
<CustomObject>
    <label>Objective Type</label>
    <nameField>
        <label>Objective Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Auto_Create_Objective__c.field-meta.xml
<CustomField>
    <fullName>BI_Auto_Create_Objective__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto-Create Objective</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Description__c.field-meta.xml
<CustomField>
    <fullName>BI_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Division__c.field-meta.xml
<CustomField>
    <fullName>BI_Division__c</fullName>
    <label>Division</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Division</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Measure__c.field-meta.xml
<CustomField>
    <fullName>BI_Measure__c</fullName>
    <label>Measure</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Objective_Measure</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Objective_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Objective Category</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>BI_Objective_Category__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Category__c</referenceTo>
    <relationshipLabel>Objective Types</relationshipLabel>
    <relationshipName>Objective_Types</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Objective_Name__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Name__c</fullName>
    <label>Objective Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Region__c.field-meta.xml
<CustomField>
    <fullName>BI_Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Region</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Relevant_Plans__c.field-meta.xml
<CustomField>
    <fullName>BI_Relevant_Plans__c</fullName>
    <label>Relevant Plans</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Divisional Plan</fullName>
            </value>
            <value>
                <fullName>Regional Plan</fullName>
            </value>
            <value>
                <fullName>Territory Plan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Target_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_Target_Date__c</fullName>
    <label>Target Date</label>
    <type>Date</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Target_Value__c.field-meta.xml
<CustomField>
    <fullName>BI_Target_Value__c</fullName>
    <label>Target Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/BI_Objectives__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Division__c.field-meta.xml
<CustomField>
    <fullName>BI_Division__c</fullName>
    <description>The Sales Division on the objective owner&apos;s user record</description>
    <formula>TEXT(Owner:User.BI_Objective_Division__c)</formula>
    <inlineHelpText>The Sales Division on the objective owner&apos;s user record</inlineHelpText>
    <label>Division</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Divisional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Divisional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divisional Plan</label>
    <referenceTo>BI_Divisional_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Focus_Accounts__c.field-meta.xml
<CustomField>
    <fullName>BI_Focus_Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Focus Accounts</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Category__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BI_Objective_Category__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Category__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Type</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (((2 AND 3) OR (4 AND 5) OR (6 AND 7)) OR 8 OR 9 OR 10)</booleanFilter>
        <errorMessage>The selected Objective Type is not valid for the type of Plan you are creating this Objective On</errorMessage>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Territory Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Territory Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Regional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Regional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Divisional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Divisional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>notContain</operation>
            <value>Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Account Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Description__c</field>
            <operation>equals</operation>
            <value>(2019)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Type__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Regional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Regional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Plan</label>
    <referenceTo>BI_Regional_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Territory_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Territory_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Plan</label>
    <referenceTo>BI_Territory_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/BI_Regional_Plan__c.object-meta.xml
<CustomObject>
    <label>Regional Plan</label>
    <nameField>
        <label>Regional Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regional Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/fields/BI_Division__c.field-meta.xml
<CustomField>
    <fullName>BI_Division__c</fullName>
    <formula>TEXT(Owner:User.BI_Objective_Division__c)</formula>
    <label>Division</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/fields/BI_Divisional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Divisional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divisional Plan</label>
    <referenceTo>BI_Divisional_Plan__c</referenceTo>
    <relationshipLabel>Regional Plans</relationshipLabel>
    <relationshipName>Regional_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/BI_Territory_Plan__c.object-meta.xml
<CustomObject>
    <label>Territory Plan</label>
    <nameField>
        <label>Territory Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/fields/BI_Region__c.field-meta.xml
<CustomField>
    <fullName>BI_Region__c</fullName>
    <formula>Owner:User.Sales_Region__c</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Territory_Plan__c/fields/BI_Regional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Regional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Plan</label>
    <referenceTo>BI_Regional_Plan__c</referenceTo>
    <relationshipLabel>Territory Plans</relationshipLabel>
    <relationshipName>Territory_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/classes/BI_PushObjectives.cls
/**************************************************************************

Name : BI_PushObjectives
===========================================================================
Purpose : This class is used to Push the Objecitves for particular Relevant Plan.
===========================================================================
History:
--------
VERSION    AUTHOR         DATE           DETAIL          DESCRIPTION
1.0       Sasi Naik    18/May/207        Created
***************************************************************************/
public class BI_PushObjectives{
    
    //This method is to createt he objecitves records when the user are selected the realted palns in the Objecitves Type record.
    @AuraEnabled
    public static String CreateRelevantPlanObjectives(String objectiveTypeid,String validyear) {
        String Successvalue = '';
        String DPRecordTypeId = '';
        String RPRecordTypeId = '';
        String TPRecordTypeId = '';
        String APRecordTypeId = '';
        
        //To Collect the Objective Category Ids into the set
        Set<Id> ObjectiveCategoryIds = new Set<Id>();
        Set<String> ObjectiveTypeNames = new Set<String>(); //added 2019-11 BI Sales Planning Enhancements
        //To Collect the Relevant Plans Ids into the set
        Set<String> relevantplanSet = new Set<String>();
        List<String> relevantplan = new List<String>();
        List<String> listregion = new List<String>();
        List<String> listdivisional = new List<String>();
        List<String> ObjYear = new List<String>();
        
        //those list will collect the records to process to functionalities
        List<BI_Objective_Type__c> listobjtype = new List<BI_Objective_Type__c>();
        List<BI_Divisional_Plan__c> listdivisionalPlan = new List<BI_Divisional_Plan__c>();
        List<BI_Regional_Plan__c> listRegionalPlan = new List<BI_Regional_Plan__c>();
        List<BI_Territory_Plan__c> listTerritoryPlan = new List<BI_Territory_Plan__c>();
        List<BI_Objectives__c> listBIsObjective = new List<BI_Objectives__c>();
        List<BI_Objectives__c> listOldBIsObjective = new List<BI_Objectives__c>();
        
        //string to collect the prefix of the oobject
        String DPlan_prefix = Schema.SObjectType.BI_Divisional_Plan__c.getKeyPrefix();
        String RPlan_prefix = Schema.SObjectType.BI_Regional_Plan__c.getKeyPrefix();
        String TPlan_prefix = Schema.SObjectType.BI_Territory_Plan__c.getKeyPrefix();
        List<BI_Objectives__c> insertnewObj = new List<BI_Objectives__c>();
        
        Set<String> uDivision = new Set<String>();
        Set<String> uRegional = new Set<String>();
        List<String> relatedplans = new List<String>();
        
        //SOQL to collect the Objective Type record information
        listobjtype = [Select Id,
                       Name,
                       BI_Objective_Name__c,
                       BI_Description__c,
                       BI_Focus_Accounts__c,
                       BI_Measure__c,
                       BI_Target_Date__c,
                       BI_Target_Value__c,
                       BI_Objective_Category__c,
                       BI_Relevant_Plans__c,
                       BI_Auto_Create_Objective__c,
                       BI_Active__c,
                       BI_Region__c,
                       BI_Division__c,
                       BI_Valid_Objective_Year__c,
                       OwnerId
                       FROM BI_Objective_Type__c
                       WHERE BI_Active__c =:BI_UtilityCls.TRUEVALUE
                       AND ID =:objectiveTypeid
                       LIMIT 1];
        
        
        for (BI_Objective_Type__c objtype : listobjtype){
            ObjectiveCategoryIds.add(objtype.BI_Objective_Category__c);
            ObjectiveTypeNames.add(objtype.BI_Objective_Name__c); //added 2019-11 BI Sales Planning Enhancements
            uDivision.add(objtype.BI_Division__c);
            uRegional.add(objtype.BI_Region__c);
            if(String.isNotBlank(objtype.BI_Region__c)){
                String[] selectedregionvalues = objtype.BI_Region__c.split(';');
                //System.debug(LoggingLevel.INFO, '*** selectedregionvalues: ' + selectedregionvalues);
                for(String sr:selectedregionvalues){
                    listregion.add(sr);
                    
                }
            }
            
            if(String.isNotBlank(objtype.BI_Division__c)){
                String[] selecteddivisionvalues = objtype.BI_Division__c.split(';');
                for(String sd:selecteddivisionvalues){
                    // if(sd == BI_UtilityCls.ALLVALUE){
                    //     AllDivisional = BI_UtilityCls.TRUEVALUE;
                    // }
                    listdivisional.add(sd);
                    //}
                }
            }   
            //relatedplans.add(objtype.BI_Relevant_Plans__c);
            if(String.isNotBlank(objtype.BI_Relevant_Plans__c)){
                relatedplans = objtype.BI_Relevant_Plans__c.split(';');
            }
        }
        
        
        String sDivisioanlPlan = '';
        String sRegionalPlan = '';
        String sTerritoryPlan = '';
        //Collecting the multi pick list values into the string for different selected plans
        for(String rp:relatedplans){
            if(rp == BI_UtilityCls.DIVISIONALPLAN){
                sDivisioanlPlan = rp;
                //System.debug(LoggingLevel.INFO, '*** sDivisioanlPlan: ' + sDivisioanlPlan);
            } else if(rp == BI_UtilityCls.REGIONALPLAN){
                sRegionalPlan = rp;
            } else if(rp == BI_UtilityCls.TERRITORYPLAN){
                sTerritoryPlan = rp;
            } 
        }
        
        Set<String> allPlansids= new Set<String>();
        Map<Id, String> divMap = new Map<Id, String>(); //added 2019-11 BI Sales Planning Enhancements
        Map<Id, String> regMap = new Map<Id, String>(); //added 2019-11 BI Sales Planning Enhancements
        Map<Id, String> terMap = new Map<Id, String>(); //added 2019-11 BI Sales Planning Enhancements
        //checking the divisional plan exisitng in the multi pick list vlaues
        if(String.isNotBlank(sDivisioanlPlan) && uDivision.size()>0){
            
            listdivisionalPlan = [Select Id, BI_Plan_Owner_Employee_Id__c from BI_Divisional_Plan__c //2019-11 BI Sales Planning Enhancements
                                  WHERE BI_Divisional_Plan_Year__c =:validyear 
                                  AND BI_Division__c IN:listdivisional
                                  Limit 10000];
            
            if(listdivisionalPlan.size()>0){ 
                Set<Id> divids = new Set<Id>();
                for(BI_Divisional_Plan__c div : listdivisionalPlan){
                    divids.add(div.Id);
                    divMap.put(div.Id, div.BI_Plan_Owner_Employee_Id__c); //added 2019-11 BI Sales Planning Enhancements
                }       
                List<BI_Objectives__c> divobjlist = new List<BI_Objectives__c>();
                divobjlist = [Select Id,
                              Name,
                              BI_Objective_Category__c,
                              BI_Objective_Type__c,
                              BI_Divisional_Plan__c
                              FROM BI_Objectives__c
                              WHERE BI_Objective_Category__c IN:ObjectiveCategoryIds
                              AND Name IN :ObjectiveTypeNames  //added 2019-11 BI Sales Planning Enhancements
                              AND BI_Objective_Type__c =:objectiveTypeid
                              AND BI_Divisional_Plan__c IN:divids
                              LIMIT 10000];
                Set<Id> odivids = new Set<Id>();
                for(BI_Objectives__c odiv : divobjlist){
                    odivids.add(odiv.BI_Divisional_Plan__c);
                }                               
                if(listdivisionalPlan.size()>0){
                    
                    DPRecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJACTIVES,BI_UtilityCls.DIVISIONALOBJECTIVE);
                    //Schema.SObjectType.BI_Objectives__c.getRecordTypeInfosByName().get(BI_UtilityCls.DIVISIONALOBJECTIVE).getRecordTypeId();
                    for(BI_Divisional_Plan__c dps:listdivisionalPlan){
                        if(!odivids.contains(dps.Id)){
                            allPlansids.add(dps.Id);
                        }   
                    }
                }
            }
        }
        
        //checking the Regional plan exisitng in the multi pick List vlaues
        if(String.isNotBlank(sRegionalPlan) && (listregion.size()>0 || listdivisional.size()>0)){
            
            listRegionalPlan = [Select Id, BI_Plan_Owner_Employee_Id__c from BI_Regional_Plan__c //2019-11 BI Sales Planning Enhancements
                                WHERE BI_Regional_Plan_Year__c =:validyear
                                AND  (BI_Division__c IN:listdivisional
                                      OR BI_Region__c IN: listregion)
                                Limit 10000];
            if(listRegionalPlan.size()>0){ 
                Set<Id> regids = new Set<Id>();
                for(BI_Regional_Plan__c reg : listRegionalPlan){
                    regids.add(reg.Id);
                    regMap.put(reg.Id, reg.BI_Plan_Owner_Employee_Id__c); //added 2019-11 BI Sales Planning Enhancements
                } 
                //System.debug(LoggingLevel.DEBUG, '*** regids: ' + regids);      
                List<BI_Objectives__c> regobjlist = new List<BI_Objectives__c>();
                regobjlist = [Select Id,
                              Name,
                              BI_Objective_Category__c,
                              BI_Objective_Type__c,
                              BI_Regional_Plan__c
                              FROM BI_Objectives__c
                              WHERE BI_Objective_Category__c IN:ObjectiveCategoryIds
                              AND Name IN :ObjectiveTypeNames  //added 2019-11 BI Sales Planning Enhancements
                              AND BI_Objective_Type__c =:objectiveTypeid
                              AND BI_Regional_Plan__c IN:regids
                              LIMIT 10000];
                // System.debug(LoggingLevel.DEBUG, '*** regobjlist.size(): ' + regobjlist.size());
                // System.debug(LoggingLevel.DEBUG, '*** regobjlist: ' + regobjlist);
                Set<Id> oregids = new Set<Id>();
                for(BI_Objectives__c oreg : regobjlist){
                    oregids.add(oreg.BI_Regional_Plan__c);
                }
                // System.debug(LoggingLevel.DEBUG, '*** oregids: ' + oregids);   
                
                if(listRegionalPlan.size()>0){
                    RPRecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJACTIVES,BI_UtilityCls.REGIONALOBJECTIVE);
                    //Schema.SObjectType.BI_Objectives__c.getRecordTypeInfosByName().get(BI_UtilityCls.REGIONALOBJECTIVE).getRecordTypeId();
                    for(BI_Regional_Plan__c rps:listRegionalPlan){
                        if(!oregids.contains(rps.Id)){
                            allPlansids.add(rps.Id);
                        }
                    }   
                }    
            }                   
        }
        
        //checking the Territory plan exisitng in the multi pickl vlaues
        if(String.isNotBlank(sTerritoryPlan) && (listregion.size()>0 || listdivisional.size()>0)){
            
            listTerritoryPlan = [Select Id, BI_Plan_Owner_Employee_Id__c from BI_Territory_Plan__c //2019-11 BI Sales Planning Enhancements
                                 WHERE BI_Territory_Plan_Year__c =:validyear 
                                 AND  (BI_Division__c IN:listdivisional
                                       OR BI_Region__c IN: listregion)
                                 Limit 10000];
            if(listTerritoryPlan.size()>0){ 
                Set<Id> terrids = new Set<Id>();
                for(BI_Territory_Plan__c terr : listTerritoryPlan){
                    terrids.add(terr.Id);
                    terMap.put(terr.Id, terr.BI_Plan_Owner_Employee_Id__c); //added 2019-11 BI Sales Planning Enhancements
                }       
                List<BI_Objectives__c> terrobjlist = new List<BI_Objectives__c>();
                terrobjlist = [Select Id,
                               Name,
                               BI_Objective_Category__c,
                               BI_Objective_Type__c,
                               BI_Territory_Plan__c
                               FROM BI_Objectives__c
                               WHERE BI_Objective_Category__c IN:ObjectiveCategoryIds
                               AND Name IN :ObjectiveTypeNames  //added 2019-11 BI Sales Planning Enhancements
                               AND BI_Objective_Type__c =:objectiveTypeid
                               AND BI_Territory_Plan__c IN:terrids
                               LIMIT 10000];
                //System.debug(LoggingLevel.DEBUG, '*** terrobjlist: ' + terrobjlist);
                Set<Id> oterrids = new Set<Id>();
                for(BI_Objectives__c oterr : terrobjlist){
                    oterrids.add(oterr.BI_Territory_Plan__c);
                }
                //System.debug(LoggingLevel.DEBUG, '*** oterrids: ' + oterrids);  
                
                if(listTerritoryPlan.size()>0){
                    TPRecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJACTIVES,BI_UtilityCls.TERRITORYOBJECTIVE);
                    for(BI_Territory_Plan__c tps:listTerritoryPlan){
                        if(!oterrids.contains(tps.Id)){
                            allPlansids.add(tps.Id);
                        }
                    }
                }   
            }                       
        }   
        
        Set<String> newObjTypeids = new Set<String>();
        Set<String> newObjCategids = new Set<String>();
        Set<String> newObjNames = new Set<String>(); //added 2019-11 BI Sales Planning Enhancements
        Set<String> newPlansids = new Set<String>();
        //System.debug(LoggingLevel.DEBUG, '*** allPlansids: ' + allPlansids);
        for(BI_Objective_Type__c objtype:listobjtype ){
            if(allPlansids.size()>0){
                for(String a:allPlansids){
                    
                    String myIdPrefix = String.valueOf(a).substring(0,3);
                    String empId = ''; //added 2019-11 BI Sales Planning Enhancements
                    // System.debug(LoggingLevel.DEBUG, '*** a: ' + a);
                    // System.debug(LoggingLevel.DEBUG, '*** myIdPrefix: ' + myIdPrefix);
                    BI_Objectives__c biObj = new BI_Objectives__c();
                    if(myIdPrefix == DPlan_prefix){
                        biObj.BI_Divisional_Plan__c = a;
                        biObj.RecordTypeId = DPRecordTypeId;
                        empId = divMap.get(a); //added 2019-11 BI Sales Planning Enhancements
                    } else if(myIdPrefix == RPlan_prefix){  
                        biObj.BI_Regional_Plan__c = a;
                        biObj.RecordTypeId = RPRecordTypeId;
                        empId = regMap.get(a); //added 2019-11 BI Sales Planning Enhancements
                    } else if(myIdPrefix == TPlan_prefix){
                        biObj.BI_Territory_Plan__c = a;
                        biObj.RecordTypeId = TPRecordTypeId;
                        empId = terMap.get(a); //added 2019-11 BI Sales Planning Enhancements
                    } 
                    biObj.BI_Auto_Created__c = BI_UtilityCls.TRUEVALUE;
                    biObj.BI_Objective_Category__c = objtype.BI_Objective_Category__c;
                    biObj.BI_Objective_Type__c = objectiveTypeid;
                    biObj.Name = objtype.BI_Objective_Name__c + ' (' + empId + ', ' + validyear + ')' ; //added 2019-11 BI Sales Planning Enhancements
                    biObj.BI_Template_Description__c = objtype.BI_Description__c;
                    biObj.BI_Focus_Accounts__c = objtype.BI_Focus_Accounts__c; //added 2019-11 BI Sales Planning Enhancements
                    biObj.BI_Measure__c = objtype.BI_Measure__c; //added 2019-11 BI Sales Planning Enhancements
                    biObj.BI_Target_Value__c = objtype.BI_Target_Value__c; //added 2019-11 BI Sales Planning Enhancements
                    biObj.BI_End_Date__c = objtype.BI_Target_Date__c; //added 2019-11 BI Sales Planning Enhancements
                    newObjTypeids.add(objtype.Id);
                    newObjCategids.add(objtype.BI_Objective_Category__c);
                    newObjNames.add(objtype.Name); //added 2019-11 BI Sales Planning Enhancements
                    newPlansids.add(a);
                    listBIsObjective.add(biObj);
                }
            }
        }
        
        //checking the listBIsObjective size greater than 0 to insert the records and also showinf the success or failure message
        if(listBIsObjective.size()>0){              
            DataBase.insert(listBIsObjective,BI_UtilityCls.FALSEVALUE);
            Successvalue = System.Label.BI_PushObjectiveSuccessMsg;
        } else {
            Successvalue = System.Label.BI_PushObjectiveFailureMsg;
        }
        
        return Successvalue;  
    }
    
    // to featch the Valid Objecttive year picklist values from Objectives Object and pass it to the UI 
    @AuraEnabled
    public static List<String> getValidObjectiveYearPickListvalues(){
        List<String> Vpickvalues = BI_UtilityCls.getPicklistValues(BI_UtilityCls.OBJACTIVESTYPE,BI_UtilityCls.VALIDOBJACTIVESYEAR);
        return Vpickvalues;
    }
}