_Source/force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency HOL</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/Agency_Branch.recordType-meta.xml
<RecordType>
    <fullName>Agency_Branch</fullName>
    <active>true</active>
    <label>Agency Branch</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/BI_Proposal_Request_Form__c.object-meta.xml
<CustomObject>
    <label>Proposal Request Form</label>
    <nameField>
        <displayFormat>PRF-{00000}</displayFormat>
        <label>Proposal Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Legal_Review_Required__c.field-meta.xml
<CustomField>
    <fullName>BI_Legal_Review_Required__c</fullName>
    <label>Legal Review Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>BI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Pricing_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>BI_Sales_Organization__c</fullName>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Organization</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Stage__c.field-meta.xml
<CustomField>
    <fullName>BI_Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Proposal_Request_Form_Status</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/BI_Stage_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_Stage_Last_Modified_Date__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Stage Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/fields/SIP_Country__c.field-meta.xml
<CustomField>
    <fullName>SIP_Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/BI_Stage_Or_Status_History__c.object-meta.xml
<CustomObject>
    <label>Stage/Status History</label>
    <nameField>
        <displayFormat>SSH-{00000}</displayFormat>
        <label>Stage/Status History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage/Status Histories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Duration__c.field-meta.xml
<CustomField>
    <fullName>BI_Duration__c</fullName>
    <label>Duration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>BI_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Stage/Status Histories</relationshipLabel>
    <relationshipName>Opportunties_Stage_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Opportunity_Status_From__c.field-meta.xml
<CustomField>
    <fullName>BI_Opportunity_Status_From__c</fullName>
    <label>Opportunity Stage From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Opportunity_StageName</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Opportunity_Status_To__c.field-meta.xml
<CustomField>
    <fullName>BI_Opportunity_Status_To__c</fullName>
    <label>Opportunity Stage To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Opportunity_StageName</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Proposal_Request_Form__c.field-meta.xml
<CustomField>
    <fullName>BI_Proposal_Request_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal Request Form</label>
    <referenceTo>BI_Proposal_Request_Form__c</referenceTo>
    <relationshipLabel>Stage/Status Histories</relationshipLabel>
    <relationshipName>Proposal_Request_Form_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Stage_Or_Status_Changed_By__c.field-meta.xml
<CustomField>
    <fullName>BI_Stage_Or_Status_Changed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stage/Status Changed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pricing_Request_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>BI_Opportunity_Name__c</fullName>
    <formula>IF( NOT(ISBLANK(Account.BI_Abbreviated_Account_Name__c)),Account.BI_Abbreviated_Account_Name__c+&apos; - &apos;+
CASE(
MONTH(  CloseDate ), 
1, 
&quot;Q1&quot; , 
2, 
&quot;Q1&quot;, 
3, 
&quot;Q1&quot;, 
4, 
&quot;Q2&quot;, 
5, 
&quot;Q2&quot;, 
6, 
&quot;Q2&quot;, 
7, 
&quot;Q3&quot;, 
8, 
&quot;Q3&quot;, 
9, 
&quot;Q3&quot;, 
10, 
&quot;Q4&quot;, 
11, 
&quot;Q4&quot;, 
12, 
&quot;Q4&quot;, 
&quot;None&quot;
)+&apos; - &apos;+TEXT(YEAR(CloseDate ))+&apos; - &apos;+ Name  
,  LEFT(Account.Name,15)+&apos; - &apos;+
CASE(
MONTH(CloseDate ), 
1, 
&quot;Q1&quot; , 
2, 
&quot;Q1&quot;, 
3, 
&quot;Q1&quot;, 
4, 
&quot;Q2&quot;, 
5, 
&quot;Q2&quot;, 
6, 
&quot;Q2&quot;, 
7, 
&quot;Q3&quot;, 
8, 
&quot;Q3&quot;, 
9, 
&quot;Q3&quot;, 
10, 
&quot;Q4&quot;, 
11, 
&quot;Q4&quot;, 
12, 
&quot;Q4&quot;, 
&quot;None&quot;
)+&apos; - &apos;+TEXT(YEAR(CloseDate))+&apos; - &apos;+ Name)</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Primary_Opportunity_Inbox_Email__c.field-meta.xml
<CustomField>
    <fullName>BI_Primary_Opportunity_Inbox_Email__c</fullName>
    <label>Primary Opportunity Inbox Email</label>
    <type>Email</type>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>BI_Sales_Organization__c</fullName>
    <inlineHelpText>Indicates the Sales Organization (i.e. North America, Latin America, APAC, EMEAI)  of the Opportunity owner. This field will be automatically completed once the opportunity is saved. You have the option to edit value if needed</inlineHelpText>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Organization</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Stage_Last_Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>BI_Stage_Last_Modified_Date__c</fullName>
    <defaultValue>Now()</defaultValue>
    <label>Stage Last Modified Date</label>
    <type>DateTime</type>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Tactical_Request_Form_Attached__c.field-meta.xml
<CustomField>
    <fullName>BI_Tactical_Request_Form_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please ensure the Tactical Request form is attached before checking the box</inlineHelpText>
    <label>Tactical Request Form Attached</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Tactical_Request_Form_TMC_Attached__c.field-meta.xml
<CustomField>
    <fullName>BI_Tactical_Request_Form_TMC_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tactical Request Form Attached</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/Opportunity/fields/BI_Travel_Agency_Request_Form_Attached__c.field-meta.xml
<CustomField>
    <fullName>BI_Travel_Agency_Request_Form_Attached__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Travel Agency Request Form Attached</label>
    <type>Checkbox</type>
</CustomField>

_Source/force-app/main/default/objects/User/fields/Sales_Region__c.field-meta.xml
<CustomField>
    <fullName>Sales_Region__c</fullName>
    <label>Sales Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/objects/User/fields/SIP_Country__c.field-meta.xml
<CustomField>
    <fullName>SIP_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/User/fields/User_Region__c.field-meta.xml
<CustomField>
    <fullName>User_Region__c</fullName>
    <formula>IF(  ISBLANK(Location__c), &quot;Other&quot;, 

IF( CONTAINS(&quot;HKGSS:TYOSS:SINSS:SELSS:TPESS:BKKSS:HKGSZ:TYOSO:SINSZ:TYOVW:AKLSS:TYOSV:NGOSS:HKGVW:FUKSS:SYDSS:OSASO:RORCS:HIJSA:OSASS:GUMUZ:JKTSS:MNLGA:KULGA:GUMSS:KWACS:TYOSZ:MAJCS:SDJSS:PEKSS:GUMSZ:HKGSV:SELSZ:CANSS:SHASS:SDJSA:TPESZ:PEKSV:CTUSS:SHASV:HGHSS:MNLSS:SGNSS:TYORR:MNLRR&quot;, Location__c), &quot;APAC&quot;,

IF(
CONTAINS(&quot;DELGA:DELSS:DELIS:LHRSS:KWIGA:LONSS:FRASS:LONVU:MOWGA:DXBGA:BAHGA:CDGSS:DUBSS:PARSS:TLVSS:FRAVU:AMSSS:LONSN:BRUSS:LISSS:MXPSS:ARNSS:LONVG:FRASC:EDISS:ZRHSS:ROMSS:BHXSS:MANSS:BFSSS:FRASZ:LHRSC:LHRSN:AMSVU:GLASS:MADSS:BCNSS:BRUSZ:FCOSS:GVASS&quot;, Location__c), &quot;EMEAI&quot;,

IF(
CONTAINS(&quot;SDQTO:MEXTO:SLPTO:MTYUZ:SAORO:CUUTO:PTYUZ:SAOUZ:GUATO:SJUSS:BJXSS:GIGSS:LIMUZ:UIOTO:LIMTO:BZESS:SJOTO:GDLTO:GUASS:UIOUZ:POSSS:MGASS:MTYTO:GIGTO:AGUTO:EZETO:MGATO:PTYTO:BOGTO:BUEUZ:SJOUZ:SAOSS:SCLTO:BUESS:BUETO:BOGSS:SAPSS:MEXSS:RIOSS:CCSSS:TGUTO:MEXVG:TAMTO:SAPTO:BZETO:SALTO:SDQSS:GRURO:SALSS:MEXUZ:CCSTO:EZEUZ:TGUUZ:SCLSS:SCLUZ:GRUUZ:VERTO:QROTO:MIDTO:EZE00:QROSS:GIGUZ:VERSS:BJXTO:BOGUZ&quot;, Location__c), &quot;Latin America&quot;, &quot;North America&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Organization</label>
    <type>Text</type>
</CustomField>

_Source/force-app/main/default/classes/BI_OpportunityTriggerHandler.cls
/**********************************************************************
   Name:  BI_OpportunityTriggerHandler
   ======================================================
   ======================================================
   Purpose:
   -------
   Deal with the DML for Opportuntiy
   ======================================================
   ======================================================
   History
   -------
   VERSION  AUTHOR               DATE              DETAIL            
   1.0     Sasi Naik             20/06/2017        INITIAL DEVELOPMENT          
   2.0     Yolande Anjargholi    09/25/2017        TMC Tactical added
 ***********************************************************************/
public class BI_OpportunityTriggerHandler implements SIP_Triggers.Handler {
    private static boolean rflag = BI_UtilityCls.TRUEVALUE;
    private static boolean aflag = BI_UtilityCls.TRUEVALUE;
    private static boolean uflag = BI_UtilityCls.TRUEVALUE;
    private static boolean birflag = BI_UtilityCls.TRUEVALUE;
    public List < Opportunity > Newopty;
    public List < Opportunity > Oldopty;
    public Map < Id, Opportunity > mapNewopty;
    public Map < Id, Opportunity > mapOldopty;
    //This method will initiate the trigger on which event the method need to call
    public void handle() {
        if (Trigger.isInsert) {
            Newopty = (List < Opportunity > ) Trigger.new;
            mapNewopty = (Map < Id, Opportunity > ) Trigger.newMap;
        } else if (Trigger.isUpdate) {
            Newopty = (List < Opportunity > ) Trigger.new;
            mapNewopty = (Map < Id, Opportunity > ) Trigger.newMap;
            mapOldopty = (Map < Id, Opportunity > ) Trigger.oldMap;
           
        }

        if (Trigger.isUpdate && Trigger.isAfter) {
            //passing the newmpa and oldmap values to the method
            if (Test.isRunningTest()){
                rflag = true;
            }
            if (rflag) {
             
                CreateOpportunityStageNameHistoryRecord(mapNewopty, mapOldopty);

                rflag = BI_UtilityCls.FALSEVALUE;
            }
        }

        if (Trigger.isInsert && Trigger.isAfter) {
            //passing the newmpa and oldmap values to the method
            if (aflag) {
                CreatePRRecord(mapNewopty);

                aflag = BI_UtilityCls.FALSEVALUE;
            }
        }


        if (Trigger.isInsert && Trigger.isBefore) {
            //passing the newmpa and oldmap values to the method
            List < Opportunity > insertoptylist = new List < Opportunity > ();
            for (Opportunity op: Newopty) {
                insertoptylist.add(op);
            }

            if (insertoptylist.size() > 0) {
                //if(BI_CheckRecursive.runOnce()){
                AssignVlauesBeforeInsertRecord(insertoptylist);
                // }
            }
        }

        if (Trigger.isUpdate && Trigger.isBefore) {
            if (uflag) {
                CreatePRRecord(mapNewopty);
                //ValidateTMCContactPRRecord(mapNewopty,mapOldopty);
                uflag = BI_UtilityCls.FALSEVALUE;
            }
        }
    }

    //This method will create the Pricing status vlaue change history into the object.Like tracking the time and to know more information about the status.
    private void AssignVlauesBeforeInsertRecord(List < Opportunity > newlist) {
      Set<String> accoutnids = new Set<String>();
      List<Account> newacclist = new List<Account>();
      List < User > loginuserinfo = [Select Id, Name, Email, Sales_Region__c, User_Region__c, SIP_Country__c From User where Id =: UserInfo.getUserId() limit 1];
      for (user u: loginuserinfo) {
        for(Opportunity opp:newlist){
            opp.Name = opp.BI_Opportunity_Name__c;
            accoutnids.add(opp.AccountId);
              if(String.isBlank(opp.BI_Sales_Organization__c)){
                    opp.BI_Sales_Organization__c = u.User_Region__c;
                }
          }
      }
      if(accoutnids.size()>0){
        newacclist = [Select Id,Name,RecordType.DeveloperName From Account Where Id IN:accoutnids 
                        AND (RecordType.DeveloperName =:BI_UtilityCls.CORPORATE
                        OR  RecordType.DeveloperName =:BI_UtilityCls.AGENCY_BRANCH
                        OR RecordType.DeveloperName =:BI_UtilityCls.AGENCY)
                        LIMIT 50000];
      }

      if(newacclist.size()>0){
        for(Opportunity op:newlist){
            if(accoutnids.contains(op.AccountId) && 
                (op.RecordTypeId == BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OPPORTUNTIYOBJ, BI_UtilityCls.CORPORATEOPTYRECORDTYPE) ||
                 op.RecordTypeId == BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OPPORTUNTIYOBJ, BI_UtilityCls.GLOBALCONTRACTOPTYRECORDTYPE))){
                    op.BI_Primary_Opportunity_Inbox_Email__c = System.label.BI_Opportunity_Non_UCS_Account_Inbox_Email;
                }
            }
        }

    }

      //This method will create the Pricing status vlaue change history into the object.Like tracking the time and to know more information about the status.
    private void CreatePRRecord(Map < Id, Opportunity > mapNewopty) {
        List < BI_Proposal_Request_Form__c > insertlistPricingReuest = new List < BI_Proposal_Request_Form__c > ();
        List < Opportunity > newlostopty = new List < Opportunity > ();
        for (Opportunity opp: mapNewopty.values()) {
            if((opp.BI_Tactical_Request_Form_Attached__c && !mapOldopty.get(opp.Id).BI_Tactical_Request_Form_Attached__c) ||
               (opp.BI_Travel_Agency_Request_Form_Attached__c && !mapOldopty.get(opp.Id). BI_Travel_Agency_Request_Form_Attached__c) ||
               (opp.BI_Tactical_Request_Form_TMC_Attached__c && !mapOldopty.get(opp.Id). BI_Tactical_Request_Form_TMC_Attached__c)){
            if (opp.BI_Tactical_Request_Form_Attached__c || opp.BI_Travel_Agency_Request_Form_Attached__c || opp.BI_Tactical_Request_Form_TMC_Attached__c) {
                BI_Proposal_Request_Form__c preq = new BI_Proposal_Request_Form__c();
                preq.BI_Opportunity__c = opp.Id;
                preq.BI_Legal_Review_Required__c = BI_UtilityCls.YES;
                if (opp.BI_Tactical_Request_Form_Attached__c) {
                    preq.RecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJPRICINGREQUEST, BI_UtilityCls.PRICINGRETACINCRECORDTYPE);
                    preq.BI_Stage__c = BI_UtilityCls.SUBMIT;
                } else if (opp.BI_Travel_Agency_Request_Form_Attached__c) {
                    preq.RecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJPRICINGREQUEST, BI_UtilityCls.PRICINGREQTMCCONTRACTRECORDTYPE);
                    preq.BI_Stage__c = BI_UtilityCls.SUBMITFORBUILD;
                } else if (opp.BI_Tactical_Request_Form_TMC_Attached__c) {
                	preq.RecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.OBJPRICINGREQUEST, BI_UtilityCls.PRICINGRETACINCTMCRECORDTYPE);
                    preq.BI_Stage__c = BI_UtilityCls.SUBMITFORBUILD;
                }
                insertlistPricingReuest.add(preq);
            } //end  1st if
               } // end 2nd if
        } //end for

        if (insertlistPricingReuest.size() > 0) {
            Database.insert(insertlistPricingReuest, BI_UtilityCls.FALSEVALUE);
        }
    } //end method

    //This method will create the Pricing status vlaue change history into the object.Like tracking the time and to know more information about the status.
    private void CreateOpportunityStageNameHistoryRecord(Map < Id, Opportunity > mapNewopty, Map < Id, Opportunity > mapOldopty) {
        //To Collect the Pricing Request Ids into the set
        Set < Id > OpportuntiyIds = new Set < Id > ();
        //List < Opportunity > updateopty = new List < Opportunity > ();
        // Setting default value to 0 in the intial
        String Dayss = '0';
        String Hourss = '0';
        String Minutess = '0';

        Set < Id > legalset = new Set < Id > ();
        Set < Id > signatoryset = new Set < Id > ();
        Set < Id > contractleadset = new Set < Id > ();

        List < BI_Stage_Or_Status_History__c > listprireqhis = new List < BI_Stage_Or_Status_History__c > ();
        List < Opportunity > newlistpricingrequest = new List < Opportunity > ();

        for (Opportunity prireq: mapNewopty.values()) {           
            if (prireq.StageName != mapOldopty.get(prireq.Id).StageName) {
                            
                Datetime startDate = mapOldopty.get(prireq.Id).BI_Stage_Last_Modified_Date__c;
                if (mapOldopty.get(prireq.Id).BI_Stage_Last_Modified_Date__c == null) {
                    startDate = mapOldopty.get(prireq.Id).LastModifiedDate; // Start date
                }
                //Datetime startDate = mapOldopty.get(prireq.Id).LastModifiedDate; // Start date
                Datetime endDate = system.now(); //End Date

                integer Days = math.round(math.floor(Double.valueOf((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))));
                integer Hours = math.mod(integer.valueOf((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60)), 24);
                integer Minutes = math.mod(Integer.valueOf((endDate.getTime() - startDate.getTime()) / (1000 * 60)), 60);

                BI_Stage_Or_Status_History__c prirqhis = new BI_Stage_Or_Status_History__c();
                prirqhis.BI_Opportunity_Status_From__c = String.valueOf(mapOldopty.get(prireq.Id).StageName);
                prirqhis.BI_Opportunity_Status_To__c = prireq.StageName;
                prirqhis.BI_Stage_Or_Status_Changed_By__c = UserInfo.getUserId();
                prirqhis.BI_Opportunity__c = prireq.Id;
                prirqhis.RecordTypeId = BI_UtilityCls.getRecordTypeIdByAPIName(BI_UtilityCls.STAGEORSTATUSHISTORYOBJAPI, BI_UtilityCls.OPTYSTAGEHISTORYRECORDTYPE);
               

                if (Integer.valueOf(Days) > 1) {
                    Dayss = String.valueOf(Days) + ' ' + BI_UtilityCls.DAYS;
                } else {
                    Dayss = String.valueOf(Days) + ' ' + BI_UtilityCls.DAY;
                }

                Hourss = '(' + String.valueOf(Hours) + ' H' + ')';
                Minutess = '(' + String.valueOf(Minutes) + ' M' + ')';

                prirqhis.BI_Duration__c = Dayss + ' ' + Hourss + ' ' + Minutess;
                listprireqhis.add(prirqhis);
               
            }
            //if condition to check the listprireqhis size greater than 0 to insert the record.
            if (listprireqhis.size() > 0) {
                Database.insert(listprireqhis, BI_UtilityCls.FALSEVALUE);
            }
        }
    }
}