_Source/force-app/main/default/objects/Account/recordTypes/Agency.recordType-meta.xml
<RecordType>
    <fullName>Agency</fullName>
    <active>true</active>
    <label>Agency HOL</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/Agency_Branch.recordType-meta.xml
<RecordType>
    <fullName>Agency_Branch</fullName>
    <active>true</active>
    <label>Agency Branch</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/BI_International_Account.recordType-meta.xml
<RecordType>
    <fullName>BI_International_Account</fullName>
    <active>true</active>
    <label>Custom Account</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/BI_Membership_Group.recordType-meta.xml
<RecordType>
    <fullName>BI_Membership_Group</fullName>
    <active>true</active>
    <label>Membership Group</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/BI_Membership_Sub_Group.recordType-meta.xml
<RecordType>
    <fullName>BI_Membership_Sub_Group</fullName>
    <active>true</active>
    <label>Membership Sub-Group</label>
</RecordType>

_Source/force-app/main/default/objects/Account/recordTypes/Corporate.recordType-meta.xml
<RecordType>
    <fullName>Corporate</fullName>
    <active>true</active>
    <label>Corporate</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Account_Plan__c/BI_Account_Plan__c.object-meta.xml
<CustomObject>
    <label>Account Plan</label>
    <nameField>
        <label>Account Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Account_Plan__c/fields/BI_Status__c.field-meta.xml
<CustomField>
    <fullName>BI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Active for Plan Year</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Account_Plan__c/recordTypes/BI_Agency_Account_Plan.recordType-meta.xml
<RecordType>
    <fullName>BI_Agency_Account_Plan</fullName>
    <active>true</active>
    <label>Agency Account Plan</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Account_Plan__c/recordTypes/BI_Corporate_Account_Plan.recordType-meta.xml
<RecordType>
    <fullName>BI_Corporate_Account_Plan</fullName>
    <active>true</active>
    <label>Corporate Account Plan</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Conversation_Topic__c/BI_Conversation_Topic__c.object-meta.xml
<CustomObject>
    <label>Conversation Topic</label>
    <nameField>
        <label>Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Conversation Topics</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Conversation_Topic__c/fields/BI_Objective_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aligned Objective Type</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Available_for_Conversation_Topics__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Type__c</referenceTo>
    <relationshipLabel>Conversation Topics</relationshipLabel>
    <relationshipName>Conversation_Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Divisional_Plan__c/BI_Divisional_Plan__c.object-meta.xml
<CustomObject>
    <label>Divisional Plan</label>
    <nameField>
        <label>Divisional Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Divisional Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Type__c/BI_Objective_Type__c.object-meta.xml
<CustomObject>
    <label>Objective Type</label>
    <nameField>
        <label>Objective Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objective Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Region__c.field-meta.xml
<CustomField>
    <fullName>BI_Region__c</fullName>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BI_Region</valueSetName>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objective_Type__c/fields/BI_Valid_Objective_Year__c.field-meta.xml
<CustomField>
    <fullName>BI_Valid_Objective_Year__c</fullName>
    <label>Valid Objective Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
            <value>
                <fullName>2038</fullName>
            </value>
            <value>
                <fullName>2039</fullName>
            </value>
            <value>
                <fullName>2040</fullName>
            </value>
            <value>
                <fullName>2041</fullName>
            </value>
            <value>
                <fullName>2042</fullName>
            </value>
            <value>
                <fullName>2043</fullName>
            </value>
            <value>
                <fullName>2044</fullName>
            </value>
            <value>
                <fullName>2045</fullName>
            </value>
            <value>
                <fullName>2046</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/BI_Objectives__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objectives Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Account_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Account_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plan</label>
    <referenceTo>BI_Account_Plan__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Divisional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Divisional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divisional Plan</label>
    <referenceTo>BI_Divisional_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Objective_Type__c.field-meta.xml
<CustomField>
    <fullName>BI_Objective_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Objective Type</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (((2 AND 3) OR (4 AND 5) OR (6 AND 7)) OR 8 OR 9 OR 10)</booleanFilter>
        <errorMessage>The selected Objective Type is not valid for the type of Plan you are creating this Objective On</errorMessage>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Territory Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Territory Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Regional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Regional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>contains</operation>
            <value>Divisional Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Divisional Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Lookup_Identifier__c</field>
            <operation>notContain</operation>
            <value>Plan</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Account Objective</value>
        </filterItems>
        <filterItems>
            <field>BI_Objective_Type__c.BI_Description__c</field>
            <operation>equals</operation>
            <value>(2019)</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BI_Objective_Type__c</referenceTo>
    <relationshipLabel>Objectives</relationshipLabel>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Regional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Regional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Regional Plan</label>
    <referenceTo>BI_Regional_Plan__c</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/fields/BI_Status__c.field-meta.xml
<CustomField>
    <fullName>BI_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

_Source/force-app/main/default/objects/BI_Objectives__c/recordTypes/BI_Account_Objecitve.recordType-meta.xml
<RecordType>
    <fullName>BI_Account_Objecitve</fullName>
    <active>true</active>
    <description>Objective record type used to capture Account Objectives.</description>
    <label>Account Objective</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Objectives__c/recordTypes/BI_Divisional_Objective.recordType-meta.xml
<RecordType>
    <fullName>BI_Divisional_Objective</fullName>
    <active>true</active>
    <description>Objective record type used to capture Divisional Objectives.</description>
    <label>Divisional Objective</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Objectives__c/recordTypes/BI_Regional_Objective.recordType-meta.xml
<RecordType>
    <fullName>BI_Regional_Objective</fullName>
    <active>true</active>
    <description>Objective record type used to track Regional Objectives.</description>
    <label>Regional Objective</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Objectives__c/recordTypes/BI_Territory_Objective.recordType-meta.xml
<RecordType>
    <fullName>BI_Territory_Objective</fullName>
    <active>true</active>
    <description>Objective record type used to track Regional Objectives.</description>
    <label>Territory Objective</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Project__c/BI_Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/BI_Proposal_Request_Form__c.object-meta.xml
<CustomObject>
    <label>Proposal Request Form</label>
    <nameField>
        <displayFormat>PRF-{00000}</displayFormat>
        <label>Proposal Request Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Request Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/recordTypes/BI_Corporate_Proposal_Request_Form.recordType-meta.xml
<RecordType>
    <fullName>BI_Corporate_Proposal_Request_Form</fullName>
    <active>true</active>
    <label>Corporate Contract Proposal Request Form</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/recordTypes/BI_PassPlus_Proposal_Request_Form.recordType-meta.xml
<RecordType>
    <fullName>BI_PassPlus_Proposal_Request_Form</fullName>
    <active>true</active>
    <label>PassPlus Proposal Request Form</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/recordTypes/BI_Tactical_Incentive_Proposal_Request_Form.recordType-meta.xml
<RecordType>
    <fullName>BI_Tactical_Incentive_Proposal_Request_Form</fullName>
    <active>true</active>
    <label>Tactical Incentive (Corporate) Proposal Request Form</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/recordTypes/BI_Tactical_Incentive_TMC_Proposal_Request_Form.recordType-meta.xml
<RecordType>
    <fullName>BI_Tactical_Incentive_TMC_Proposal_Request_Form</fullName>
    <active>true</active>
    <label>Tactical Incentive (Agency) Proposal Request Form</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Proposal_Request_Form__c/recordTypes/BI_TMC_Contract_Proposal_Request_Form.recordType-meta.xml
<RecordType>
    <fullName>BI_TMC_Contract_Proposal_Request_Form</fullName>
    <active>true</active>
    <label>Agency Contract Proposal Request Form</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/BI_Regional_Plan__c.object-meta.xml
<CustomObject>
    <label>Regional Plan</label>
    <nameField>
        <label>Regional Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regional Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Regional_Plan__c/fields/BI_Divisional_Plan__c.field-meta.xml
<CustomField>
    <fullName>BI_Divisional_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Divisional Plan</label>
    <referenceTo>BI_Divisional_Plan__c</referenceTo>
    <relationshipLabel>Regional Plans</relationshipLabel>
    <relationshipName>Regional_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/BI_Stage_Or_Status_History__c.object-meta.xml
<CustomObject>
    <label>Stage/Status History</label>
    <nameField>
        <displayFormat>SSH-{00000}</displayFormat>
        <label>Stage/Status History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage/Status Histories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/fields/BI_Proposal_Request_Form__c.field-meta.xml
<CustomField>
    <fullName>BI_Proposal_Request_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal Request Form</label>
    <referenceTo>BI_Proposal_Request_Form__c</referenceTo>
    <relationshipLabel>Stage/Status Histories</relationshipLabel>
    <relationshipName>Proposal_Request_Form_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/recordTypes/BI_Lead_Status_History.recordType-meta.xml
<RecordType>
    <fullName>BI_Lead_Status_History</fullName>
    <active>true</active>
    <label>Lead Status History</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/recordTypes/BI_Opportunity_Stage_History.recordType-meta.xml
<RecordType>
    <fullName>BI_Opportunity_Stage_History</fullName>
    <active>true</active>
    <label>Opportunity Stage History</label>
</RecordType>

_Source/force-app/main/default/objects/BI_Stage_Or_Status_History__c/recordTypes/BI_Proposal_Request_Form_Stage_History.recordType-meta.xml
<RecordType>
    <fullName>BI_Proposal_Request_Form_Stage_History</fullName>
    <active>true</active>
    <label>Proposal Request Form Stage History</label>
</RecordType>

_Source/force-app/main/default/objects/Case/recordTypes/Business_Insight_Case.recordType-meta.xml
<RecordType>
    <fullName>Business_Insight_Case</fullName>
    <active>true</active>
    <businessProcess>Business Insight Support</businessProcess>
    <label>BI Support Request</label>
</RecordType>

_Source/force-app/main/default/objects/Case/recordTypes/Business_Insight_Case_Release.recordType-meta.xml
<RecordType>
    <fullName>Business_Insight_Case_Release</fullName>
    <active>true</active>
    <businessProcess>Business Insight Release</businessProcess>
    <label>BI Release Request</label>
</RecordType>

_Source/force-app/main/default/objects/Contact/recordTypes/Business.recordType-meta.xml
<RecordType>
    <fullName>Business</fullName>
    <active>true</active>
    <label>Business</label>
</RecordType>

_Source/force-app/main/default/objects/Opportunity/recordTypes/BI_Corporate.recordType-meta.xml
<RecordType>
    <fullName>BI_Corporate</fullName>
    <active>true</active>
    <businessProcess>BI - Corporate Contract</businessProcess>
    <description>Create a corporate contract Opportunity (New Acquisition/Renewal/Amendment)</description>
    <label>Corporate Contract</label>
</RecordType>

_Source/force-app/main/default/objects/Opportunity/recordTypes/BI_Global_Contract.recordType-meta.xml
<RecordType>
    <fullName>BI_Global_Contract</fullName>
    <active>false</active>
    <businessProcess>BI - Corporate Contract</businessProcess>
    <description>Deprecated in BI Release 2019-05/06</description>
    <label>Global Contract</label>
</RecordType>

_Source/force-app/main/default/objects/Opportunity/recordTypes/BI_Tactical_Incentive_Pricing.recordType-meta.xml
<RecordType>
    <fullName>BI_Tactical_Incentive_Pricing</fullName>
    <active>true</active>
    <businessProcess>BI - Tactical Incentive %28Corporate%29</businessProcess>
    <description>Create a Corporate tactical / incentive opportunity</description>
    <label>Tactical Incentive (Corporate)</label>
</RecordType>

_Source/force-app/main/default/objects/Opportunity/recordTypes/BI_TMC_Contract.recordType-meta.xml
<RecordType>
    <fullName>BI_TMC_Contract</fullName>
    <active>true</active>
    <businessProcess>BI - Agency Contract</businessProcess>
    <description>Create an Agency Contract opportunity (Acquisition/Renewal/Amendment)</description>
    <label>Agency Contract</label>
</RecordType>

_Source/force-app/main/default/classes/BI_UtilityCls.cls
/**************************************************************************

Name : BI_UtilityCls

===========================================================================
Purpose : 
===========================================================================
History:
--------
VERSION    AUTHOR         DATE            DETAIL          DESCRIPTION
1.0        Sasi Naik      17/May/2017     Created         CSR:    
2.0        Yolande Anj    16/May/2018     Updated         Included missed objects and record type definitions   
***************************************************************************/

public without sharing class BI_UtilityCls {
	
    public static Boolean isTriggerFired = false;
    
    //objects
    public static Final String OBJSTATUS  = 'BI_Status__c';
    public static Final String DIVISIONALOBJECTIVE  = 'BI_Divisional_Objective';
    public static Final String REGIONALOBJECTIVE  = 'BI_Regional_Objective';
    public static Final String TERRITORYOBJECTIVE  = 'BI_Territory_Objective';
    public static Final String OBJACCOUNTPLAN = 'BI_Account_Plan__c';
    public static Final String OBJACTIVES  = 'BI_Objectives__c';
    public static Final String LEADOBJECT  = 'Lead';
    public static Final String CASEOBJECT  = 'Case';
    public static Final String CONTACTOBJECT = 'Contact';
    public static Final String CONVOTOPIC  = 'BI_Conversation_Topic__c';
	public static Final String ProjectObject  = 'BI_Project__c';
    
    //Record Types
    
    public static Final String OBJCORPCONTRACTRECORDTYPE = 'Corporate_Contract';
    
    //Contact Record Types
    public static Final String BUSCONTACTRECORDTYPE = 'Business';
    
    //Opportunity Record Types
    public static Final String TMCCONTRACTOPTYRECORDTYPE  = 'BI_TMC_Contract';
    public static Final String OPPTACINCTMCRECORDTYPE = 'BI_Tactical_Incentive_TMC';
    public static Final String CORPORATEOPTYRECORDTYPE  = 'BI_Corporate';
    public static Final String GLOBALCONTRACTOPTYRECORDTYPE  = 'BI_Global_Contract';
    public static Final String OTHEROPTYRECORDTYPE = 'BI_Other';
    
    //Account Record Types
    public static Final String ACCTAGENCYBRANCHRECORDTYPE = 'Agency_Branch';
    public static Final String ACCTAGENCYHOLRECORDTYPE = 'Agency';
    public static Final String ACCTCORPRECORDTYPE = 'Corporate'; 
	public static Final String ACCTNONUCSRECORDTYPE = 'BI_International_Account';
    public static Final String ACCMEMGROUPRECORDTYPE = 'BI_Membership_Group';
    public static Final String ACCMEMSUBGROUPRECORDTYPE = 'BI_Membership_Sub_Group';
    
    //CASE RECORD TYPES
    public static Final String BISUPCASERECORDTYPE = 'Business_Insight_Case';
    public static Final String BIRELCASERECORDTYPE = 'Business_Insight_Case_Release';
    
    
    //Objective Record Types
    public static Final String ACCOUNTOBJECTIVE  = 'BI_Account_Objecitve';
    
    //Account Plan Record Types
    public static Final String AGENCYACCTPLANRECORDTYPE = 'BI_Agency_Account_Plan';
    public static Final String CORPACCTPLANRECORDTYPE = 'BI_Corporate_Account_Plan';
    
        //Stage/Status History Record Type API Names
    public static Final String LEADSTATUSHISTORYRECORDTYPE  = 'BI_Lead_Status_History';
    public static Final String OPTYSTAGEHISTORYRECORDTYPE  = 'BI_Opportunity_Stage_History';
    public static Final String PRICINGREQSTAGEHISTORYRECORDTYPE  = 'BI_Proposal_Request_Form_Stage_History';

    public static Final String PRICINGREQCPRPORATERECORDTYPE  = 'BI_Corporate_Proposal_Request_Form';
    public static Final String PRICINGRETACINCRECORDTYPE  = 'BI_Tactical_Incentive_Proposal_Request_Form';
    public static Final String PRICINGREQPASSPLUSRECORDTYPE  = 'BI_PassPlus_Proposal_Request_Form';
    public static Final String PRICINGREQTMCCONTRACTRECORDTYPE  = 'BI_TMC_Contract_Proposal_Request_Form';
	public static Final String PRICINGRETACINCTMCRECORDTYPE = 'BI_Tactical_Incentive_TMC_Proposal_Request_Form';


    public static Final String OPPORTUNITYOBJECTIVE  = 'Opportunity';
    public static Final String DIVISIONALPLAN  = 'Divisional Plan';
    public static Final String REGIONALPLAN  = 'Regional Plan';
    public static Final String TERRITORYPLAN  = 'Territory Plan';
    public static Final String ACCOUNTPLAN  = 'Account Plan';
    public static Final String CORPORATE  = 'Corporate';
    public static Final String TRAVELAGENCY  = 'Travel Agency';
    public static Final String CORPORATEGLOBAL  = 'Corporate (global)';
    public static Final String ACCOUNTOBJ  = 'Account';
    public static Final String OPPORTUNTIYOBJ  = 'Opportunity';


    public static Final Boolean TRUEVALUE  = true;
    public static Final Boolean FALSEVALUE  = false;
    public static Final String NULLVALUE  = null;
    public static Final String DAY  = 'Day';
    public static Final String DAYS  = 'Days';
    public static Final String HOURS  = 'H';
    public static Final String MINUTES  = 'M';
    public static Final String NONE  ='--NONE--';
    public static Final String PICKLIST  ='PICKLIST';
    public static Final String MULTIPICKLIST  ='MULTIPICKLIST';
    public static Final String AGENCY  ='Agency';
    public static Final String TESTNAME  ='test name';
    public static Final String NOTVALIDPRF  = 'Not Valid Proposal Request Form';
    public static Final String ALLVALUE  = 'All';


    public static Final String PRICINGNEGOPROPOSAL = 'Pricing/Negotiation/Proposal';
    public static Final String LEGAL = 'Legal';
    public static Final String SIGNATORY = 'Signatory';
    public static Final String CONTRACTLEAD = 'Contract Lead';
    public static Final String LOST = 'LOS';
    public static Final String LOSSOFACQUISITION = 'LOA';
    public static Final String INACTIVE = 'INA';
    public static Final String RENEWED = 'NCR';
    public static Final String WITHDRAWNCANCELLED = 'Withdrawn/Cancelled';
    public static Final String SUBMIT = 'Submitted';
    public static Final String SUBMITFORBUILD = 'Submitted for build';
    public static String DRF_STAGE = 'Draft';
    public static String RFB_STAGE = 'RFB';
    public static Final String ACTIVEVALUE = 'Active';

    public static Final String YES = 'Yes';
    public static Final String OTHER = 'Other';
    public static Final String NORTHAMERICA = 'North America';
    public static Final String LATINAMERICA = 'Latin America';
    public static Final String APAC = 'APAC';
    public static Final String EMEAI = 'EMEAI';

    public static Final String REGION = 'BI_Region__c';

    public static Final String NONUCSACCOUNTRECORDTYPE = 'BI_International_Account';
    public static Final String SMEACCOUNTRECORDTYPE = 'BI_SME_Account';
    public static Final String AGENCY_BRANCH = 'Agency_Branch';
    public static Final String AGENCY_SUMMARY = 'PL_Agency_Summary';
    public static Final String AGENT = 'Agent';

    //BI RELEASE 2019-08 Lead Management
    public static Final String CLOSEDORLOST = 'Closed (Not Converted)';
    public static Final String CLOSEDCONVERTED = 'Converted';
    public static Final String LEADSTATUS1 = 'Pre-Work';
    public static Final String LEADSTATUS2 = 'Engaged';

    public static Final String PRICEGRIDAPINAME  = 'BI_Pricing_Grid__c';
    public static Final String DIVISIONALPLANAPIOBJECT  = 'BI_Divisional_Plan__c';
    public static Final String REGIONALPLANAPIOBJECT  = 'BI_Regional_Plan__c';
    public static Final String OBJACTIVESTYPE  = 'BI_Objective_Type__c';
    public static Final String VALIDOBJACTIVESYEAR  = 'BI_Valid_Objective_Year__c';
    public static Final String OBJPRICINGREQUEST  = 'BI_Proposal_Request_Form__c';
    public static Final String OBJCONTRACT  = 'SIP_Contract__c';
     // Field Set
    public static Final String PRICING_MASS_FIELD_SET  = 'Pricing_Mass_POC_Field_Set';
    public static Final String CONVOTOPIC_MASS_FIELD_SET  = 'Conversation_Topic_Mass_Field_Set';
	public static Final String PROJECT_MASS_FIELD_SET  = 'Project_Mass_Field_Set';

    //Object API Names 
    public static Final String STAGEORSTATUSHISTORYOBJAPI  = 'BI_Stage_Or_Status_History__c';
    // Objective Type - Region, Division
    public static Final String OBJECTIVETYPEREGION = 'ARN - SALES';
    public static Final String OBJECTIVETYPEDIVISION = 'BRAZIL SALES';
    // User - Region, Division
    public static Final String USERREGION = 'ARN - SALES';
    public static Final String USERDIVISION = 'BRAZIL SALES';
    // Plan Year
    public static Final String PLAN_YEAR = '2017';
    public static Final String PLAN_YEAR_A = '2016';
    // Opportunity Stage 
    public static Final String STAGE_FIRST = 'Prework & Qualification';
    public static Final String STAGE_SECOND = 'Data Analysis/Review';
    public static Final String STAGE_THIRD = 'Pricing/Negotiation/Proposal';
    //User Country
    public static Final String USER_COUNTRY = 'ZAIRE';
    public static Final String BRAZIL = 'BRAZIL';
    public static Final String ARGENTINA = 'ARGENTINA';
    public static Final String MEXICO = 'MEXTO';
     public static Final String MEXICOUN = 'MEXICO';
    public static Final String BELIZE = 'BELIZE';
    public static Final String ACCOUNT_CONTACT_RELATIONSHIP_ROLE = 'Signatory;Contract Lead;';
    public static Final String CONTRACT_CATEGORY = 'New';
    public static Final String OPPORTUNITY_TACTICAL_INCENTIVE_RECORD_TYPE = 'BI_Tactical_Incentive_Pricing';
    public static Final String TYOSS = 'TYOSS';
    public static Final String LHRSS ='LHRSS';
    public static Final String PREVIEW = 'Preview';
    public static Final String APFJAPAN = 'APF Japan';
    

    
    /*
     * Method : getPicklistValues
     * Purpose : Get field picklist values based on object name and Field Name
     * Params : String strObjName   - ApI Name of the object
                String strFieldName - API Name of the picklist field
     */
    public static List<String> getPicklistValues(String strObjName, String strFieldName){ 
     
      List<String> lstPickvals = new List<String>();
      Schema.SObjectType targetType = Schema.getGlobalDescribe().get(strObjName);//From the Object Api name retrieving the SObject
      Sobject ObjectName = targetType.newSObject();
      Schema.sObjectType sobjType = ObjectName.getSObjectType(); //grab the sobject that was passed
      Schema.DescribeSObjectResult sobjDesc = sobjType.getDescribe(); //describe the sobject
      Map<String, Schema.SObjectField> mapField = sobjDesc.fields.getMap(); //get a map of fields for the passed sobject
      List<Schema.PicklistEntry> listPickListVals = mapField.get(strFieldName).getDescribe().getPickListValues(); 
      
      for (Schema.PicklistEntry entry : listPickListVals) {
        lstPickvals.add(entry.getValue());
      }
      return lstPickvals;
  }
    /*
     * Method : getFieldSetAllFields
     * Purpose : Get all FieldPaths from fieldset
     * Params : String objectName   - ApI Name of the object
                String fieldSetName - API Name of the fieldSet field
     */
    
  public static List<String> getFieldSetAllFieldPaths(String objectName, String fieldSetName) {
      Schema.SObjectType targetType = Schema.getGlobalDescribe().get(objectName);
      Schema.DescribeSObjectResult describe = targetType.getDescribe();
      Map<String, Schema.FieldSet> fsMap = describe.fieldSets.getMap();
      Schema.FieldSet fs = fsMap.get(fieldSetName);
      List<Schema.FieldSetMember> fieldSetList = fs.getFields();

      List<String> allFieldPathsList = new List<String>(); // Object's API name
      for(Schema.FieldSetMember fieldSet : fieldSetList) {
        allFieldPathsList.add(fieldSet.getFieldPath());
      }

      return allFieldPathsList; 
  }
 
  /*
     * Method : getRecordTypeIdByAPIName
     * Purpose : Get the reordtype Id of the particular object
     * Params : String objectName   - ApI Name of the object
                String fieldSetName - API Name of the fieldAPIName
     */
  public static String getRecordTypeIdByAPIName(String objectName, String fieldAPIName) {
    return [select Id,DeveloperName from RecordType where SobjectType =:objectName and DeveloperName=:fieldAPIName].Id;
  }
}